<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Authentication;

use Core\Authentication\CoreAuth;
use FortisApiLib\ConfigurationDefaults;
use Core\Request\Parameters\HeaderParam;

/**
 * Utility class for authorization and token management.
 */
class DeveloperIdManager extends CoreAuth implements DeveloperIdCredentials
{
    /**
     * @var array
     */
    private $config;

    public function __construct(array $config)
    {
        $this->config = $config;
        parent::__construct(HeaderParam::init('developer-id', $this->getDeveloperId())->requiredNonEmpty());
    }

    /**
     * String value for developerId.
     */
    public function getDeveloperId(): string
    {
        return $this->config['developerId'] ?? ConfigurationDefaults::DEVELOPER_ID;
    }

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $developerId Developer ID
     */
    public function equals(string $developerId): bool
    {
        return $developerId == $this->getDeveloperId();
    }
}
