<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisApiLib\Models\Async2;

/**
 * Builder for model Async2
 *
 * @see Async2
 */
class Async2Builder
{
    /**
     * @var Async2
     */
    private $instance;

    private function __construct(Async2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Async 2 Builder object.
     */
    public static function init(): self
    {
        return new self(new Async2());
    }

    /**
     * Sets code field.
     *
     * @param string|null $value
     */
    public function code(?string $value): self
    {
        $this->instance->setCode($value);
        return $this;
    }

    /**
     * Sets link field.
     *
     * @param string|null $value
     */
    public function link(?string $value): self
    {
        $this->instance->setLink($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Async 2 object.
     */
    public function build(): Async2
    {
        return CoreHelper::clone($this->instance);
    }
}
