<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisApiLib\Models\Data9;
use FortisApiLib\Models\Result;
use FortisApiLib\Models\Status5;

/**
 * Builder for model Data9
 *
 * @see Data9
 */
class Data9Builder
{
    /**
     * @var Data9
     */
    private $instance;

    private function __construct(Data9 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Data 9 Builder object.
     */
    public static function init(): self
    {
        return new self(new Data9());
    }

    /**
     * Sets result field.
     *
     * @param Result|null $value
     */
    public function result(?Result $value): self
    {
        $this->instance->setResult($value);
        return $this;
    }

    /**
     * Sets status field.
     *
     * @param Status5|null $value
     */
    public function status(?Status5 $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Data 9 object.
     */
    public function build(): Data9
    {
        return CoreHelper::clone($this->instance);
    }
}
