<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisApiLib\Models\Data38;

/**
 * Builder for model Data38
 *
 * @see Data38
 */
class Data38Builder
{
    /**
     * @var Data38
     */
    private $instance;

    private function __construct(Data38 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Data 38 Builder object.
     */
    public static function init(): self
    {
        return new self(new Data38());
    }

    /**
     * Sets result Code field.
     *
     * @param bool|null $value
     */
    public function resultCode(?bool $value): self
    {
        $this->instance->setResultCode($value);
        return $this;
    }

    /**
     * Sets merchant ID field.
     *
     * @param string|null $value
     */
    public function merchantId(?string $value): self
    {
        $this->instance->setMerchantId($value);
        return $this;
    }

    /**
     * Sets apple Pay field.
     *
     * @param bool|null $value
     */
    public function applePay(?bool $value): self
    {
        $this->instance->setApplePay($value);
        return $this;
    }

    /**
     * Sets google Pay field.
     *
     * @param bool|null $value
     */
    public function googlePay(?bool $value): self
    {
        $this->instance->setGooglePay($value);
        return $this;
    }

    /**
     * Sets apple Pay Domains field.
     *
     * @param array[]|null $value
     */
    public function applePayDomains(?array $value): self
    {
        $this->instance->setApplePayDomains($value);
        return $this;
    }

    /**
     * Sets message field.
     *
     * @param string|null $value
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Sets google JWT field.
     *
     * @param string|null $value
     */
    public function googleJwt(?string $value): self
    {
        $this->instance->setGoogleJwt($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Data 38 object.
     */
    public function build(): Data38
    {
        return CoreHelper::clone($this->instance);
    }
}
