<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisApiLib\Models\Device1;

/**
 * Builder for model Device1
 *
 * @see Device1
 */
class Device1Builder
{
    /**
     * @var Device1
     */
    private $instance;

    private function __construct(Device1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Device 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new Device1());
    }

    /**
     * Sets device binding status field.
     *
     * @param string|null $value
     */
    public function deviceBindingStatus(?string $value): self
    {
        $this->instance->setDeviceBindingStatus($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Device 1 object.
     */
    public function build(): Device1
    {
        return CoreHelper::clone($this->instance);
    }
}
