<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisApiLib\Models\EmvReceiptData;

/**
 * Builder for model EmvReceiptData
 *
 * @see EmvReceiptData
 */
class EmvReceiptDataBuilder
{
    /**
     * @var EmvReceiptData
     */
    private $instance;

    private function __construct(EmvReceiptData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Emv Receipt Data Builder object.
     */
    public static function init(): self
    {
        return new self(new EmvReceiptData());
    }

    /**
     * Sets AID field.
     *
     * @param string|null $value
     */
    public function aid(?string $value): self
    {
        $this->instance->setAid($value);
        return $this;
    }

    /**
     * Unsets AID field.
     */
    public function unsetAid(): self
    {
        $this->instance->unsetAid();
        return $this;
    }

    /**
     * Sets APPLAB field.
     *
     * @param string|null $value
     */
    public function applab(?string $value): self
    {
        $this->instance->setApplab($value);
        return $this;
    }

    /**
     * Unsets APPLAB field.
     */
    public function unsetApplab(): self
    {
        $this->instance->unsetApplab();
        return $this;
    }

    /**
     * Sets APPN field.
     *
     * @param string|null $value
     */
    public function appn(?string $value): self
    {
        $this->instance->setAppn($value);
        return $this;
    }

    /**
     * Unsets APPN field.
     */
    public function unsetAppn(): self
    {
        $this->instance->unsetAppn();
        return $this;
    }

    /**
     * Sets CVM field.
     *
     * @param string|null $value
     */
    public function cvm(?string $value): self
    {
        $this->instance->setCvm($value);
        return $this;
    }

    /**
     * Unsets CVM field.
     */
    public function unsetCvm(): self
    {
        $this->instance->unsetCvm();
        return $this;
    }

    /**
     * Sets TSI field.
     *
     * @param string|null $value
     */
    public function tsi(?string $value): self
    {
        $this->instance->setTsi($value);
        return $this;
    }

    /**
     * Unsets TSI field.
     */
    public function unsetTsi(): self
    {
        $this->instance->unsetTsi();
        return $this;
    }

    /**
     * Sets TVR field.
     *
     * @param string|null $value
     */
    public function tvr(?string $value): self
    {
        $this->instance->setTvr($value);
        return $this;
    }

    /**
     * Unsets TVR field.
     */
    public function unsetTvr(): self
    {
        $this->instance->unsetTvr();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Emv Receipt Data object.
     */
    public function build(): EmvReceiptData
    {
        return CoreHelper::clone($this->instance);
    }
}
