<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisApiLib\Models\HomePhone2;

/**
 * Builder for model HomePhone2
 *
 * @see HomePhone2
 */
class HomePhone2Builder
{
    /**
     * @var HomePhone2
     */
    private $instance;

    private function __construct(HomePhone2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Home Phone 2 Builder object.
     */
    public static function init(): self
    {
        return new self(new HomePhone2());
    }

    /**
     * Sets cc field.
     *
     * @param string|null $value
     */
    public function cc(?string $value): self
    {
        $this->instance->setCc($value);
        return $this;
    }

    /**
     * Sets subscriber field.
     *
     * @param string|null $value
     */
    public function subscriber(?string $value): self
    {
        $this->instance->setSubscriber($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Home Phone 2 object.
     */
    public function build(): HomePhone2
    {
        return CoreHelper::clone($this->instance);
    }
}
