<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisApiLib\Models\IdentityVerification5;

/**
 * Builder for model IdentityVerification5
 *
 * @see IdentityVerification5
 */
class IdentityVerification5Builder
{
    /**
     * @var IdentityVerification5
     */
    private $instance;

    private function __construct(IdentityVerification5 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Identity Verification 5 Builder object.
     */
    public static function init(): self
    {
        return new self(new IdentityVerification5());
    }

    /**
     * Sets dl state field.
     *
     * @param string|null $value
     */
    public function dlState(?string $value): self
    {
        $this->instance->setDlState($value);
        return $this;
    }

    /**
     * Unsets dl state field.
     */
    public function unsetDlState(): self
    {
        $this->instance->unsetDlState();
        return $this;
    }

    /**
     * Sets dl number field.
     *
     * @param string|null $value
     */
    public function dlNumber(?string $value): self
    {
        $this->instance->setDlNumber($value);
        return $this;
    }

    /**
     * Unsets dl number field.
     */
    public function unsetDlNumber(): self
    {
        $this->instance->unsetDlNumber();
        return $this;
    }

    /**
     * Sets ssn 4 field.
     *
     * @param string|null $value
     */
    public function ssn4(?string $value): self
    {
        $this->instance->setSsn4($value);
        return $this;
    }

    /**
     * Unsets ssn 4 field.
     */
    public function unsetSsn4(): self
    {
        $this->instance->unsetSsn4();
        return $this;
    }

    /**
     * Sets dob year field.
     *
     * @param string|null $value
     */
    public function dobYear(?string $value): self
    {
        $this->instance->setDobYear($value);
        return $this;
    }

    /**
     * Unsets dob year field.
     */
    public function unsetDobYear(): self
    {
        $this->instance->unsetDobYear();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Identity Verification 5 object.
     */
    public function build(): IdentityVerification5
    {
        return CoreHelper::clone($this->instance);
    }
}
