<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisApiLib\Models\MerchantList;
use FortisApiLib\Models\MultiTransaction1;

/**
 * Builder for model MultiTransaction1
 *
 * @see MultiTransaction1
 */
class MultiTransaction1Builder
{
    /**
     * @var MultiTransaction1
     */
    private $instance;

    private function __construct(MultiTransaction1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Multi Transaction 1 Builder object.
     *
     * @param MerchantList[] $merchantList
     */
    public static function init(array $merchantList): self
    {
        return new self(new MultiTransaction1($merchantList));
    }

    /**
     * Sets av validity time field.
     *
     * @param int|null $value
     */
    public function avValidityTime(?int $value): self
    {
        $this->instance->setAvValidityTime($value);
        return $this;
    }

    /**
     * Sets av number use field.
     *
     * @param int|null $value
     */
    public function avNumberUse(?int $value): self
    {
        $this->instance->setAvNumberUse($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Multi Transaction 1 object.
     */
    public function build(): MultiTransaction1
    {
        return CoreHelper::clone($this->instance);
    }
}
