<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisApiLib\Models\Links1;
use FortisApiLib\Models\List20;
use FortisApiLib\Models\Pagination1;
use FortisApiLib\Models\ResponseUsersCollection;
use FortisApiLib\Models\Sort1;

/**
 * Builder for model ResponseUsersCollection
 *
 * @see ResponseUsersCollection
 */
class ResponseUsersCollectionBuilder
{
    /**
     * @var ResponseUsersCollection
     */
    private $instance;

    private function __construct(ResponseUsersCollection $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Response Users Collection Builder object.
     */
    public static function init(): self
    {
        return new self(new ResponseUsersCollection());
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets list field.
     *
     * @param List20[]|null $value
     */
    public function list(?array $value): self
    {
        $this->instance->setList($value);
        return $this;
    }

    /**
     * Sets links field.
     *
     * @param Links1|null $value
     */
    public function links(?Links1 $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Sets pagination field.
     *
     * @param Pagination1|null $value
     */
    public function pagination(?Pagination1 $value): self
    {
        $this->instance->setPagination($value);
        return $this;
    }

    /**
     * Sets sort field.
     *
     * @param Sort1|null $value
     */
    public function sort(?Sort1 $value): self
    {
        $this->instance->setSort($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Response Users Collection object.
     */
    public function build(): ResponseUsersCollection
    {
        return CoreHelper::clone($this->instance);
    }
}
