<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisApiLib\Models\Response417FilterChannels;

/**
 * Builder for model Response417FilterChannels
 *
 * @see Response417FilterChannels
 */
class Response417FilterChannelsBuilder
{
    /**
     * @var Response417FilterChannels
     */
    private $instance;

    private function __construct(Response417FilterChannels $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Response 417 Filter Channels Builder object.
     */
    public static function init(): self
    {
        return new self(new Response417FilterChannels());
    }

    /**
     * Sets status Code field.
     *
     * @param int|null $value
     */
    public function statusCode(?int $value): self
    {
        $this->instance->setStatusCode($value);
        return $this;
    }

    /**
     * Sets error field.
     *
     * @param string|null $value
     */
    public function error(?string $value): self
    {
        $this->instance->setError($value);
        return $this;
    }

    /**
     * Sets message field.
     *
     * @param string|null $value
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Response 417 Filter Channels object.
     */
    public function build(): Response417FilterChannels
    {
        return CoreHelper::clone($this->instance);
    }
}
