<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisApiLib\Models\Signature1;

/**
 * Builder for model Signature1
 *
 * @see Signature1
 */
class Signature1Builder
{
    /**
     * @var Signature1
     */
    private $instance;

    private function __construct(Signature1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Signature 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new Signature1());
    }

    /**
     * Sets signature field.
     *
     * @param string|null $value
     */
    public function signature(?string $value): self
    {
        $this->instance->setSignature($value);
        return $this;
    }

    /**
     * Sets resource field.
     *
     * @param string|null $value
     */
    public function resource(?string $value): self
    {
        $this->instance->setResource($value);
        return $this;
    }

    /**
     * Sets resource id field.
     *
     * @param string|null $value
     */
    public function resourceId(?string $value): self
    {
        $this->instance->setResourceId($value);
        return $this;
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets created ts field.
     *
     * @param int|null $value
     */
    public function createdTs(?int $value): self
    {
        $this->instance->setCreatedTs($value);
        return $this;
    }

    /**
     * Sets modified ts field.
     *
     * @param int|null $value
     */
    public function modifiedTs(?int $value): self
    {
        $this->instance->setModifiedTs($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Signature 1 object.
     */
    public function build(): Signature1
    {
        return CoreHelper::clone($this->instance);
    }
}
