<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisApiLib\Models\UiPrefs1;

/**
 * Builder for model UiPrefs1
 *
 * @see UiPrefs1
 */
class UiPrefs1Builder
{
    /**
     * @var UiPrefs1
     */
    private $instance;

    private function __construct(UiPrefs1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Ui Prefs 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new UiPrefs1());
    }

    /**
     * Sets entry page field.
     *
     * @param string|null $value
     */
    public function entryPage(?string $value): self
    {
        $this->instance->setEntryPage($value);
        return $this;
    }

    /**
     * Unsets entry page field.
     */
    public function unsetEntryPage(): self
    {
        $this->instance->unsetEntryPage();
        return $this;
    }

    /**
     * Sets page size field.
     *
     * @param int|null $value
     */
    public function pageSize(?int $value): self
    {
        $this->instance->setPageSize($value);
        return $this;
    }

    /**
     * Unsets page size field.
     */
    public function unsetPageSize(): self
    {
        $this->instance->unsetPageSize();
        return $this;
    }

    /**
     * Sets report export type field.
     *
     * @param array|null $value
     */
    public function reportExportType(?array $value): self
    {
        $this->instance->setReportExportType($value);
        return $this;
    }

    /**
     * Sets process method field.
     *
     * @param array|null $value
     */
    public function processMethod(?array $value): self
    {
        $this->instance->setProcessMethod($value);
        return $this;
    }

    /**
     * Sets default terminal field.
     *
     * @param string|null $value
     */
    public function defaultTerminal(?string $value): self
    {
        $this->instance->setDefaultTerminal($value);
        return $this;
    }

    /**
     * Unsets default terminal field.
     */
    public function unsetDefaultTerminal(): self
    {
        $this->instance->unsetDefaultTerminal();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Ui Prefs 1 object.
     */
    public function build(): UiPrefs1
    {
        return CoreHelper::clone($this->instance);
    }
}
