<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Controllers;

use Core\Authentication\Auth;
use Core\Request\Parameters\BodyParam;
use Core\Request\Parameters\HeaderParam;
use Core\Request\Parameters\QueryParam;
use Core\Response\Types\ErrorType;
use CoreInterfaces\Core\Request\RequestMethod;
use FortisAPILib\Exceptions\ApiException;
use FortisAPILib\Exceptions\Response401tokenException;
use FortisAPILib\Exceptions\Response412Exception;
use FortisAPILib\Models\Expand60Enum;
use FortisAPILib\Models\ResponseTransaction;
use FortisAPILib\Models\ResponseTransactionProcessing;
use FortisAPILib\Models\V1TransactionsCcAuthOnlyKeyedRequest;
use FortisAPILib\Models\V1TransactionsCcAuthOnlyPrevTrxnRequest;
use FortisAPILib\Models\V1TransactionsCcAuthOnlySwipedRequest;
use FortisAPILib\Models\V1TransactionsCcAuthOnlyTaptopayRequest;
use FortisAPILib\Models\V1TransactionsCcAuthOnlyTerminalRequest;
use FortisAPILib\Models\V1TransactionsCcAuthOnlyTicketRequest;
use FortisAPILib\Models\V1TransactionsCcAuthOnlyTokenRequest;
use FortisAPILib\Models\V1TransactionsCcAuthOnlyWalletRequest;
use FortisAPILib\Models\V1TransactionsCcAvsOnlyKeyedRequest;
use FortisAPILib\Models\V1TransactionsCcAvsOnlyPrevTrxnRequest;
use FortisAPILib\Models\V1TransactionsCcAvsOnlySwipedRequest;
use FortisAPILib\Models\V1TransactionsCcAvsOnlyTerminalRequest;
use FortisAPILib\Models\V1TransactionsCcAvsOnlyTicketRequest;
use FortisAPILib\Models\V1TransactionsCcAvsOnlyTokenRequest;
use FortisAPILib\Models\V1TransactionsCcAvsOnlyWalletRequest;
use FortisAPILib\Models\V1TransactionsCcBalanceInquiryKeyedRequest;
use FortisAPILib\Models\V1TransactionsCcBalanceInquiryPrevTrxnRequest;
use FortisAPILib\Models\V1TransactionsCcBalanceInquirySwipedRequest;
use FortisAPILib\Models\V1TransactionsCcBalanceInquiryTerminalRequest;
use FortisAPILib\Models\V1TransactionsCcBalanceInquiryTicketRequest;
use FortisAPILib\Models\V1TransactionsCcBalanceInquiryTokenRequest;
use FortisAPILib\Models\V1TransactionsCcBalanceInquiryWalletRequest;
use FortisAPILib\Models\V1TransactionsCcForceKeyedRequest;
use FortisAPILib\Models\V1TransactionsCcForcePrevTrxnRequest;
use FortisAPILib\Models\V1TransactionsCcForceSwipedRequest;
use FortisAPILib\Models\V1TransactionsCcForceTicketRequest;
use FortisAPILib\Models\V1TransactionsCcForceTokenRequest;
use FortisAPILib\Models\V1TransactionsCcForceWalletRequest;
use FortisAPILib\Models\V1TransactionsCcRefundKeyedRequest;
use FortisAPILib\Models\V1TransactionsCcRefundPrevTrxnRequest;
use FortisAPILib\Models\V1TransactionsCcRefundSwipedRequest;
use FortisAPILib\Models\V1TransactionsCcRefundTaptopayRequest;
use FortisAPILib\Models\V1TransactionsCcRefundTerminalRequest;
use FortisAPILib\Models\V1TransactionsCcRefundTicketRequest;
use FortisAPILib\Models\V1TransactionsCcRefundTokenRequest;
use FortisAPILib\Models\V1TransactionsCcRefundWalletRequest;
use FortisAPILib\Models\V1TransactionsCcSaleKeyedRequest;
use FortisAPILib\Models\V1TransactionsCcSalePrevTrxnRequest;
use FortisAPILib\Models\V1TransactionsCcSaleSwipedRequest;
use FortisAPILib\Models\V1TransactionsCcSaleTaptopayRequest;
use FortisAPILib\Models\V1TransactionsCcSaleTerminalRequest;
use FortisAPILib\Models\V1TransactionsCcSaleTicketRequest;
use FortisAPILib\Models\V1TransactionsCcSaleTokenRequest;
use FortisAPILib\Models\V1TransactionsCcSaleWalletRequest;

class TransactionsCreditCardController extends BaseController
{
    /**
     * Create a new keyed Credit Card authorization only transaction
     *
     * @param V1TransactionsCcAuthOnlyKeyedRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCAuthOnly(V1TransactionsCcAuthOnlyKeyedRequest $body, ?array $expand = null): ResponseTransaction
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/auth-only/keyed')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Credit Card authorization only transaction using previous transaction id
     *
     * @param V1TransactionsCcAuthOnlyPrevTrxnRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCAuthOnlyPreviousTransaction(
        V1TransactionsCcAuthOnlyPrevTrxnRequest $body,
        ?array $expand = null
    ): ResponseTransaction {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/auth-only/prev-trxn')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new swiped Credit Card authorization only transaction
     *
     * @param V1TransactionsCcAuthOnlySwipedRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCAuthOnlySwiped(
        V1TransactionsCcAuthOnlySwipedRequest $body,
        ?array $expand = null
    ): ResponseTransaction {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/auth-only/swiped')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Tap To Pay Credit Card authorization only transaction
     *
     * @param V1TransactionsCcAuthOnlyTaptopayRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCAuthOnlyTapToPay(
        V1TransactionsCcAuthOnlyTaptopayRequest $body,
        ?array $expand = null
    ): ResponseTransaction {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/auth-only/taptopay')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new terminal Credit Card authorization only transaction
     *
     * @param V1TransactionsCcAuthOnlyTerminalRequest $body
     *
     * @return ResponseTransactionProcessing Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCAuthOnlyTerminal(V1TransactionsCcAuthOnlyTerminalRequest $body): ResponseTransactionProcessing
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/auth-only/terminal')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(HeaderParam::init('Content-Type', 'application/json'), BodyParam::init($body));

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransactionProcessing::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new ticket Credit Card authorization only transaction
     *
     * @param V1TransactionsCcAuthOnlyTicketRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCAuthOnlyTicket(
        V1TransactionsCcAuthOnlyTicketRequest $body,
        ?array $expand = null
    ): ResponseTransaction {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/auth-only/ticket')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new tokenized Credit Card authorization only transaction
     *
     * @param V1TransactionsCcAuthOnlyTokenRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCAuthOnlyTokenized(
        V1TransactionsCcAuthOnlyTokenRequest $body,
        ?array $expand = null
    ): ResponseTransaction {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/auth-only/token')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Wallet Credit Card authorization only transaction
     *
     * @param V1TransactionsCcAuthOnlyWalletRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCAuthOnlyWallet(
        V1TransactionsCcAuthOnlyWalletRequest $body,
        ?array $expand = null
    ): ResponseTransaction {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/auth-only/wallet')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new keyed Credit Card AVS only transaction
     *
     * @param V1TransactionsCcAvsOnlyKeyedRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCAVS(V1TransactionsCcAvsOnlyKeyedRequest $body, ?array $expand = null): ResponseTransaction
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/avs-only/keyed')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Credit Card AVS only transaction using previous transaction id
     *
     * @param V1TransactionsCcAvsOnlyPrevTrxnRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCAVSPreviousTransaction(
        V1TransactionsCcAvsOnlyPrevTrxnRequest $body,
        ?array $expand = null
    ): ResponseTransaction {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/avs-only/prev-trxn')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new swiped Credit Card AVS only transaction
     *
     * @param V1TransactionsCcAvsOnlySwipedRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCAVSSwiped(V1TransactionsCcAvsOnlySwipedRequest $body, ?array $expand = null): ResponseTransaction
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/avs-only/swiped')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new terminal Credit Card AVS only transaction
     *
     * @param V1TransactionsCcAvsOnlyTerminalRequest $body
     *
     * @return ResponseTransactionProcessing Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCAVSTerminal(V1TransactionsCcAvsOnlyTerminalRequest $body): ResponseTransactionProcessing
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/avs-only/terminal')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(HeaderParam::init('Content-Type', 'application/json'), BodyParam::init($body));

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransactionProcessing::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new ticket Credit Card AVS only transaction
     *
     * @param V1TransactionsCcAvsOnlyTicketRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCAVSTicket(V1TransactionsCcAvsOnlyTicketRequest $body, ?array $expand = null): ResponseTransaction
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/avs-only/ticket')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new tokenized Credit Card AVS only transaction
     *
     * @param V1TransactionsCcAvsOnlyTokenRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCAVSTokenized(
        V1TransactionsCcAvsOnlyTokenRequest $body,
        ?array $expand = null
    ): ResponseTransaction {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/avs-only/token')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Wallet Credit Card AVS only transaction
     *
     * @param V1TransactionsCcAvsOnlyWalletRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCAVSWallet(V1TransactionsCcAvsOnlyWalletRequest $body, ?array $expand = null): ResponseTransaction
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/avs-only/wallet')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new keyed Credit Card balance inquiry transaction
     *
     * @param V1TransactionsCcBalanceInquiryKeyedRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCBalanceInquiry(
        V1TransactionsCcBalanceInquiryKeyedRequest $body,
        ?array $expand = null
    ): ResponseTransaction {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/balance-inquiry/keyed')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Credit Card balance inquiry transaction using previous transaction id
     *
     * @param V1TransactionsCcBalanceInquiryPrevTrxnRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCBalanceInquiryPreviousTransaction(
        V1TransactionsCcBalanceInquiryPrevTrxnRequest $body,
        ?array $expand = null
    ): ResponseTransaction {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/balance-inquiry/prev-trxn')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new swiped Credit Card balance inquiry transaction
     *
     * @param V1TransactionsCcBalanceInquirySwipedRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCBalanceInquirySwiped(
        V1TransactionsCcBalanceInquirySwipedRequest $body,
        ?array $expand = null
    ): ResponseTransaction {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/balance-inquiry/swiped')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new terminal Credit Card balance inquiry transaction
     *
     * @param V1TransactionsCcBalanceInquiryTerminalRequest $body
     *
     * @return ResponseTransactionProcessing Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCBalanceInquiryTerminal(
        V1TransactionsCcBalanceInquiryTerminalRequest $body
    ): ResponseTransactionProcessing {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/balance-inquiry/terminal')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(HeaderParam::init('Content-Type', 'application/json'), BodyParam::init($body));

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransactionProcessing::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Ticket Credit Card balance inquiry transaction
     *
     * @param V1TransactionsCcBalanceInquiryTicketRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCBalanceInquiryTicket(
        V1TransactionsCcBalanceInquiryTicketRequest $body,
        ?array $expand = null
    ): ResponseTransaction {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/balance-inquiry/ticket')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new tokenized Credit Card balance inquiry transaction
     *
     * @param V1TransactionsCcBalanceInquiryTokenRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCBalanceInquiryTokenized(
        V1TransactionsCcBalanceInquiryTokenRequest $body,
        ?array $expand = null
    ): ResponseTransaction {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/balance-inquiry/token')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Wallet Credit Card balance inquiry transaction
     *
     * @param V1TransactionsCcBalanceInquiryWalletRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCBalanceInquiryWallet(
        V1TransactionsCcBalanceInquiryWalletRequest $body,
        ?array $expand = null
    ): ResponseTransaction {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/balance-inquiry/wallet')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new keyed Credit Card force transaction
     *
     * @param V1TransactionsCcForceKeyedRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCForce(V1TransactionsCcForceKeyedRequest $body, ?array $expand = null): ResponseTransaction
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/force/keyed')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Credit Card force transaction using previous transaction id
     *
     * @param V1TransactionsCcForcePrevTrxnRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCForcePreviousTransaction(
        V1TransactionsCcForcePrevTrxnRequest $body,
        ?array $expand = null
    ): ResponseTransaction {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/force/prev-trxn')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new swiped Credit Card force transaction
     *
     * @param V1TransactionsCcForceSwipedRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCForceSwiped(V1TransactionsCcForceSwipedRequest $body, ?array $expand = null): ResponseTransaction
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/force/swiped')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new ticket Credit Card force transaction
     *
     * @param V1TransactionsCcForceTicketRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCForceTicket(V1TransactionsCcForceTicketRequest $body, ?array $expand = null): ResponseTransaction
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/force/ticket')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new tokenized Credit Card force transaction
     *
     * @param V1TransactionsCcForceTokenRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCForceTokenized(
        V1TransactionsCcForceTokenRequest $body,
        ?array $expand = null
    ): ResponseTransaction {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/force/token')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Wallet Credit Card force transaction
     *
     * @param V1TransactionsCcForceWalletRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCForceWallet(V1TransactionsCcForceWalletRequest $body, ?array $expand = null): ResponseTransaction
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/force/wallet')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new keyed Credit Card refund transaction
     *
     * @param V1TransactionsCcRefundKeyedRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCRefund(V1TransactionsCcRefundKeyedRequest $body, ?array $expand = null): ResponseTransaction
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/refund/keyed')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Credit Card refund transaction using previous transaction id
     *
     * @param V1TransactionsCcRefundPrevTrxnRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCRefundPreviousTransaction(
        V1TransactionsCcRefundPrevTrxnRequest $body,
        ?array $expand = null
    ): ResponseTransaction {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/refund/prev-trxn')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new swiped Credit Card refund transaction
     *
     * @param V1TransactionsCcRefundSwipedRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCRefundSwiped(
        V1TransactionsCcRefundSwipedRequest $body,
        ?array $expand = null
    ): ResponseTransaction {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/refund/swiped')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Tap To Pay Credit Card refund transaction
     *
     * @param V1TransactionsCcRefundTaptopayRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCRefundTapToPay(
        V1TransactionsCcRefundTaptopayRequest $body,
        ?array $expand = null
    ): ResponseTransaction {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/refund/taptopay')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new terminal Credit Card refund transaction
     *
     * @param V1TransactionsCcRefundTerminalRequest $body
     *
     * @return ResponseTransactionProcessing Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCRefundTerminal(V1TransactionsCcRefundTerminalRequest $body): ResponseTransactionProcessing
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/refund/terminal')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(HeaderParam::init('Content-Type', 'application/json'), BodyParam::init($body));

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransactionProcessing::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new ticket Credit Card refund transaction
     *
     * @param V1TransactionsCcRefundTicketRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCRefundTicket(
        V1TransactionsCcRefundTicketRequest $body,
        ?array $expand = null
    ): ResponseTransaction {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/refund/ticket')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new tokenized Credit Card refund transaction
     *
     * @param V1TransactionsCcRefundTokenRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCRefundTokenized(
        V1TransactionsCcRefundTokenRequest $body,
        ?array $expand = null
    ): ResponseTransaction {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/refund/token')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Wallet Credit Card refund transaction
     *
     * @param V1TransactionsCcRefundWalletRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCRefundWallet(
        V1TransactionsCcRefundWalletRequest $body,
        ?array $expand = null
    ): ResponseTransaction {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/refund/wallet')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new keyed Credit Card sale transaction with a non hosted card form. This is an in PCI Scope
     * endpoint and requires PCI compliance verification.
     *
     * @param V1TransactionsCcSaleKeyedRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCSale(V1TransactionsCcSaleKeyedRequest $body, ?array $expand = null): ResponseTransaction
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/sale/keyed')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Credit Card sale transaction using previous transaction id
     *
     * @param V1TransactionsCcSalePrevTrxnRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCSalePreviousTransaction(
        V1TransactionsCcSalePrevTrxnRequest $body,
        ?array $expand = null
    ): ResponseTransaction {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/sale/prev-trxn')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new swiped Credit Card sale transaction
     *
     * @param V1TransactionsCcSaleSwipedRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCSaleSwiped(V1TransactionsCcSaleSwipedRequest $body, ?array $expand = null): ResponseTransaction
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/sale/swiped')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Tap To Pay Credit card sale transaction. Only supported on native iOS integrations.
     *
     * @param V1TransactionsCcSaleTaptopayRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCSaleTapToPay(
        V1TransactionsCcSaleTaptopayRequest $body,
        ?array $expand = null
    ): ResponseTransaction {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/sale/taptopay')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Credit Card Sale for card present EMV transactions using any of the Certified terminals.
     *
     * @param V1TransactionsCcSaleTerminalRequest $body
     *
     * @return ResponseTransactionProcessing Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCSaleTerminal(V1TransactionsCcSaleTerminalRequest $body): ResponseTransactionProcessing
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/sale/terminal')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(HeaderParam::init('Content-Type', 'application/json'), BodyParam::init($body));

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransactionProcessing::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Credit Card Sale using the Ticket_id obtained from the Elements form submission done
     * event.
     *
     * @param V1TransactionsCcSaleTicketRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCSaleTicket(V1TransactionsCcSaleTicketRequest $body, ?array $expand = null): ResponseTransaction
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/sale/ticket')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Credit Card Sale with a previously created token_id.
     *
     * @param V1TransactionsCcSaleTokenRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCSaleTokenized(V1TransactionsCcSaleTokenRequest $body, ?array $expand = null): ResponseTransaction
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/sale/token')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Wallet Credit Card sale transaction
     *
     * @param V1TransactionsCcSaleWalletRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ResponseTransaction Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cCSaleWallet(V1TransactionsCcSaleWalletRequest $body, ?array $expand = null): ResponseTransaction
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/sale/wallet')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body),
                QueryParam::init('expand', $expand)->serializeBy([Expand60Enum::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401tokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }
}
