<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Controllers;

use Core\Authentication\Auth;
use Core\Request\Parameters\BodyParam;
use Core\Request\Parameters\HeaderParam;
use Core\Request\Parameters\QueryParam;
use Core\Response\Types\ErrorType;
use CoreInterfaces\Core\Request\RequestMethod;
use FortisApiLib\Exceptions\Response401TokenException;
use FortisApiLib\Exceptions\Response412Exception;
use FortisApiLib\Http\ApiResponse;
use FortisApiLib\Models\ResponseTransaction;
use FortisApiLib\Models\ResponseTransactionProcessing;
use FortisApiLib\Models\V1TransactionsCcAuthOnlyKeyedRequest;
use FortisApiLib\Models\V1TransactionsCcAuthOnlyPrevTrxnRequest;
use FortisApiLib\Models\V1TransactionsCcAuthOnlySwipedRequest;
use FortisApiLib\Models\V1TransactionsCcAuthOnlyTaptopayRequest;
use FortisApiLib\Models\V1TransactionsCcAuthOnlyTerminalRequest;
use FortisApiLib\Models\V1TransactionsCcAuthOnlyTicketRequest;
use FortisApiLib\Models\V1TransactionsCcAuthOnlyTokenRequest;
use FortisApiLib\Models\V1TransactionsCcAuthOnlyWalletRequest;
use FortisApiLib\Models\V1TransactionsCcAvsOnlyKeyedRequest;
use FortisApiLib\Models\V1TransactionsCcAvsOnlyPrevTrxnRequest;
use FortisApiLib\Models\V1TransactionsCcAvsOnlySwipedRequest;
use FortisApiLib\Models\V1TransactionsCcAvsOnlyTerminalRequest;
use FortisApiLib\Models\V1TransactionsCcAvsOnlyTicketRequest;
use FortisApiLib\Models\V1TransactionsCcAvsOnlyTokenRequest;
use FortisApiLib\Models\V1TransactionsCcAvsOnlyWalletRequest;
use FortisApiLib\Models\V1TransactionsCcBalanceInquiryKeyedRequest;
use FortisApiLib\Models\V1TransactionsCcBalanceInquiryPrevTrxnRequest;
use FortisApiLib\Models\V1TransactionsCcBalanceInquirySwipedRequest;
use FortisApiLib\Models\V1TransactionsCcBalanceInquiryTerminalRequest;
use FortisApiLib\Models\V1TransactionsCcBalanceInquiryTicketRequest;
use FortisApiLib\Models\V1TransactionsCcBalanceInquiryTokenRequest;
use FortisApiLib\Models\V1TransactionsCcBalanceInquiryWalletRequest;
use FortisApiLib\Models\V1TransactionsCcForceKeyedRequest;
use FortisApiLib\Models\V1TransactionsCcForcePrevTrxnRequest;
use FortisApiLib\Models\V1TransactionsCcForceSwipedRequest;
use FortisApiLib\Models\V1TransactionsCcForceTicketRequest;
use FortisApiLib\Models\V1TransactionsCcForceTokenRequest;
use FortisApiLib\Models\V1TransactionsCcForceWalletRequest;
use FortisApiLib\Models\V1TransactionsCcRefundKeyedRequest;
use FortisApiLib\Models\V1TransactionsCcRefundPrevTrxnRequest;
use FortisApiLib\Models\V1TransactionsCcRefundSwipedRequest;
use FortisApiLib\Models\V1TransactionsCcRefundTaptopayRequest;
use FortisApiLib\Models\V1TransactionsCcRefundTerminalRequest;
use FortisApiLib\Models\V1TransactionsCcRefundTicketRequest;
use FortisApiLib\Models\V1TransactionsCcRefundTokenRequest;
use FortisApiLib\Models\V1TransactionsCcRefundWalletRequest;
use FortisApiLib\Models\V1TransactionsCcSaleKeyedRequest;
use FortisApiLib\Models\V1TransactionsCcSalePrevTrxnRequest;
use FortisApiLib\Models\V1TransactionsCcSaleSwipedRequest;
use FortisApiLib\Models\V1TransactionsCcSaleTaptopayRequest;
use FortisApiLib\Models\V1TransactionsCcSaleTerminalRequest;
use FortisApiLib\Models\V1TransactionsCcSaleTicketRequest;
use FortisApiLib\Models\V1TransactionsCcSaleTokenRequest;
use FortisApiLib\Models\V1TransactionsCcSaleWalletRequest;

class TransactionsCreditCardController extends BaseController
{
    /**
     * Create a new keyed Credit Card authorization only transaction
     *
     * @param V1TransactionsCcAuthOnlyKeyedRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccAuthOnly(V1TransactionsCcAuthOnlyKeyedRequest $body, ?array $expand = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/auth-only/keyed')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Credit Card authorization only transaction using previous transaction id
     *
     * @param V1TransactionsCcAuthOnlyPrevTrxnRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccAuthOnlyPreviousTransaction(
        V1TransactionsCcAuthOnlyPrevTrxnRequest $body,
        ?array $expand = null
    ): ApiResponse {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/auth-only/prev-trxn')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new swiped Credit Card authorization only transaction
     *
     * @param V1TransactionsCcAuthOnlySwipedRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccAuthOnlySwiped(V1TransactionsCcAuthOnlySwipedRequest $body, ?array $expand = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/auth-only/swiped')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Tap To Pay Credit Card authorization only transaction
     *
     * @param V1TransactionsCcAuthOnlyTaptopayRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccAuthOnlyTapToPay(
        V1TransactionsCcAuthOnlyTaptopayRequest $body,
        ?array $expand = null
    ): ApiResponse {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/auth-only/taptopay')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new terminal Credit Card authorization only transaction
     *
     * @param V1TransactionsCcAuthOnlyTerminalRequest $body
     *
     * @return ApiResponse Response from the API call
     */
    public function ccAuthOnlyTerminal(V1TransactionsCcAuthOnlyTerminalRequest $body): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/auth-only/terminal')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(HeaderParam::init('Content-Type', 'application/json'), BodyParam::init($body)->required());

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransactionProcessing::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new ticket Credit Card authorization only transaction
     *
     * @param V1TransactionsCcAuthOnlyTicketRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccAuthOnlyTicket(V1TransactionsCcAuthOnlyTicketRequest $body, ?array $expand = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/auth-only/ticket')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new tokenized Credit Card authorization only transaction
     *
     * @param V1TransactionsCcAuthOnlyTokenRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccAuthOnlyTokenized(V1TransactionsCcAuthOnlyTokenRequest $body, ?array $expand = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/auth-only/token')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Wallet Credit Card authorization only transaction
     *
     * @param V1TransactionsCcAuthOnlyWalletRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccAuthOnlyWallet(V1TransactionsCcAuthOnlyWalletRequest $body, ?array $expand = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/auth-only/wallet')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new keyed Credit Card AVS only transaction
     *
     * @param V1TransactionsCcAvsOnlyKeyedRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccavs(V1TransactionsCcAvsOnlyKeyedRequest $body, ?array $expand = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/avs-only/keyed')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Credit Card AVS only transaction using previous transaction id
     *
     * @param V1TransactionsCcAvsOnlyPrevTrxnRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccavsPreviousTransaction(
        V1TransactionsCcAvsOnlyPrevTrxnRequest $body,
        ?array $expand = null
    ): ApiResponse {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/avs-only/prev-trxn')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new swiped Credit Card AVS only transaction
     *
     * @param V1TransactionsCcAvsOnlySwipedRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccavsSwiped(V1TransactionsCcAvsOnlySwipedRequest $body, ?array $expand = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/avs-only/swiped')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new terminal Credit Card AVS only transaction
     *
     * @param V1TransactionsCcAvsOnlyTerminalRequest $body
     *
     * @return ApiResponse Response from the API call
     */
    public function ccavsTerminal(V1TransactionsCcAvsOnlyTerminalRequest $body): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/avs-only/terminal')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(HeaderParam::init('Content-Type', 'application/json'), BodyParam::init($body)->required());

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransactionProcessing::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new ticket Credit Card AVS only transaction
     *
     * @param V1TransactionsCcAvsOnlyTicketRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccavsTicket(V1TransactionsCcAvsOnlyTicketRequest $body, ?array $expand = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/avs-only/ticket')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new tokenized Credit Card AVS only transaction
     *
     * @param V1TransactionsCcAvsOnlyTokenRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccavsTokenized(V1TransactionsCcAvsOnlyTokenRequest $body, ?array $expand = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/avs-only/token')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Wallet Credit Card AVS only transaction
     *
     * @param V1TransactionsCcAvsOnlyWalletRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccavsWallet(V1TransactionsCcAvsOnlyWalletRequest $body, ?array $expand = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/avs-only/wallet')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new keyed Credit Card balance inquiry transaction
     *
     * @param V1TransactionsCcBalanceInquiryKeyedRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccBalanceInquiry(
        V1TransactionsCcBalanceInquiryKeyedRequest $body,
        ?array $expand = null
    ): ApiResponse {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/balance-inquiry/keyed')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Credit Card balance inquiry transaction using previous transaction id
     *
     * @param V1TransactionsCcBalanceInquiryPrevTrxnRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccBalanceInquiryPreviousTransaction(
        V1TransactionsCcBalanceInquiryPrevTrxnRequest $body,
        ?array $expand = null
    ): ApiResponse {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/balance-inquiry/prev-trxn')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new swiped Credit Card balance inquiry transaction
     *
     * @param V1TransactionsCcBalanceInquirySwipedRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccBalanceInquirySwiped(
        V1TransactionsCcBalanceInquirySwipedRequest $body,
        ?array $expand = null
    ): ApiResponse {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/balance-inquiry/swiped')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new terminal Credit Card balance inquiry transaction
     *
     * @param V1TransactionsCcBalanceInquiryTerminalRequest $body
     *
     * @return ApiResponse Response from the API call
     */
    public function ccBalanceInquiryTerminal(V1TransactionsCcBalanceInquiryTerminalRequest $body): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/balance-inquiry/terminal')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(HeaderParam::init('Content-Type', 'application/json'), BodyParam::init($body)->required());

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransactionProcessing::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Ticket Credit Card balance inquiry transaction
     *
     * @param V1TransactionsCcBalanceInquiryTicketRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccBalanceInquiryTicket(
        V1TransactionsCcBalanceInquiryTicketRequest $body,
        ?array $expand = null
    ): ApiResponse {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/balance-inquiry/ticket')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new tokenized Credit Card balance inquiry transaction
     *
     * @param V1TransactionsCcBalanceInquiryTokenRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccBalanceInquiryTokenized(
        V1TransactionsCcBalanceInquiryTokenRequest $body,
        ?array $expand = null
    ): ApiResponse {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/balance-inquiry/token')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Wallet Credit Card balance inquiry transaction
     *
     * @param V1TransactionsCcBalanceInquiryWalletRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccBalanceInquiryWallet(
        V1TransactionsCcBalanceInquiryWalletRequest $body,
        ?array $expand = null
    ): ApiResponse {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/balance-inquiry/wallet')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new keyed Credit Card force transaction
     *
     * @param V1TransactionsCcForceKeyedRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccForce(V1TransactionsCcForceKeyedRequest $body, ?array $expand = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/force/keyed')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Credit Card force transaction using previous transaction id
     *
     * @param V1TransactionsCcForcePrevTrxnRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccForcePreviousTransaction(
        V1TransactionsCcForcePrevTrxnRequest $body,
        ?array $expand = null
    ): ApiResponse {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/force/prev-trxn')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new swiped Credit Card force transaction
     *
     * @param V1TransactionsCcForceSwipedRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccForceSwiped(V1TransactionsCcForceSwipedRequest $body, ?array $expand = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/force/swiped')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new ticket Credit Card force transaction
     *
     * @param V1TransactionsCcForceTicketRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccForceTicket(V1TransactionsCcForceTicketRequest $body, ?array $expand = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/force/ticket')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new tokenized Credit Card force transaction
     *
     * @param V1TransactionsCcForceTokenRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccForceTokenized(V1TransactionsCcForceTokenRequest $body, ?array $expand = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/force/token')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Wallet Credit Card force transaction
     *
     * @param V1TransactionsCcForceWalletRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccForceWallet(V1TransactionsCcForceWalletRequest $body, ?array $expand = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/force/wallet')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new keyed Credit Card refund transaction
     *
     * @param V1TransactionsCcRefundKeyedRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccRefund(V1TransactionsCcRefundKeyedRequest $body, ?array $expand = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/refund/keyed')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Credit Card refund transaction using previous transaction id
     *
     * @param V1TransactionsCcRefundPrevTrxnRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccRefundPreviousTransaction(
        V1TransactionsCcRefundPrevTrxnRequest $body,
        ?array $expand = null
    ): ApiResponse {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/refund/prev-trxn')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new swiped Credit Card refund transaction
     *
     * @param V1TransactionsCcRefundSwipedRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccRefundSwiped(V1TransactionsCcRefundSwipedRequest $body, ?array $expand = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/refund/swiped')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Tap To Pay Credit Card refund transaction
     *
     * @param V1TransactionsCcRefundTaptopayRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccRefundTapToPay(V1TransactionsCcRefundTaptopayRequest $body, ?array $expand = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/refund/taptopay')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new terminal Credit Card refund transaction
     *
     * @param V1TransactionsCcRefundTerminalRequest $body
     *
     * @return ApiResponse Response from the API call
     */
    public function ccRefundTerminal(V1TransactionsCcRefundTerminalRequest $body): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/refund/terminal')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(HeaderParam::init('Content-Type', 'application/json'), BodyParam::init($body)->required());

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransactionProcessing::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new ticket Credit Card refund transaction
     *
     * @param V1TransactionsCcRefundTicketRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccRefundTicket(V1TransactionsCcRefundTicketRequest $body, ?array $expand = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/refund/ticket')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new tokenized Credit Card refund transaction
     *
     * @param V1TransactionsCcRefundTokenRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccRefundTokenized(V1TransactionsCcRefundTokenRequest $body, ?array $expand = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/refund/token')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Wallet Credit Card refund transaction
     *
     * @param V1TransactionsCcRefundWalletRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccRefundWallet(V1TransactionsCcRefundWalletRequest $body, ?array $expand = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/refund/wallet')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new keyed Credit Card sale transaction with a non hosted card form. This is an in PCI Scope
     * endpoint and requires PCI compliance verification.
     *
     * @param V1TransactionsCcSaleKeyedRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccSale(V1TransactionsCcSaleKeyedRequest $body, ?array $expand = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/sale/keyed')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Credit Card sale transaction using previous transaction id
     *
     * @param V1TransactionsCcSalePrevTrxnRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccSalePreviousTransaction(
        V1TransactionsCcSalePrevTrxnRequest $body,
        ?array $expand = null
    ): ApiResponse {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/sale/prev-trxn')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new swiped Credit Card sale transaction
     *
     * @param V1TransactionsCcSaleSwipedRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccSaleSwiped(V1TransactionsCcSaleSwipedRequest $body, ?array $expand = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/sale/swiped')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Tap To Pay Credit card sale transaction. Only supported on native iOS integrations.
     *
     * @param V1TransactionsCcSaleTaptopayRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccSaleTapToPay(V1TransactionsCcSaleTaptopayRequest $body, ?array $expand = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/sale/taptopay')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Credit Card Sale for card present EMV transactions using any of the Certified terminals.
     *
     * @param V1TransactionsCcSaleTerminalRequest $body
     *
     * @return ApiResponse Response from the API call
     */
    public function ccSaleTerminal(V1TransactionsCcSaleTerminalRequest $body): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/sale/terminal')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(HeaderParam::init('Content-Type', 'application/json'), BodyParam::init($body)->required());

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransactionProcessing::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Credit Card Sale using the Ticket_id obtained from the Elements form submission done
     * event.
     *
     * @param V1TransactionsCcSaleTicketRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccSaleTicket(V1TransactionsCcSaleTicketRequest $body, ?array $expand = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/sale/ticket')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Credit Card Sale with a previously created token_id.
     *
     * @param V1TransactionsCcSaleTokenRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccSaleTokenized(V1TransactionsCcSaleTokenRequest $body, ?array $expand = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/sale/token')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create a new Wallet Credit Card sale transaction
     *
     * @param V1TransactionsCcSaleWalletRequest $body
     * @param string[]|null $expand Most endpoints in the API have a way to retrieve extra data
     *        related to the current record being retrieved. For example, if the API request is
     *        for the accountvaults endpoint, and the end user also needs to know which contact
     *        the token belongs to, this data can be returned in the accountvaults endpoint
     *        request.
     *
     * @return ApiResponse Response from the API call
     */
    public function ccSaleWallet(V1TransactionsCcSaleWalletRequest $body, ?array $expand = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/transactions/cc/sale/wallet')
            ->auth(Auth::and('user-id', 'user-api-key', 'developer-id'))
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required(),
                QueryParam::init('expand', $expand)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', Response401TokenException::class))
            ->throwErrorOn('412', ErrorType::init('Precondition Failed', Response412Exception::class))
            ->type(ResponseTransaction::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }
}
