<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Account type
 * >For ACH, must be provided as either 'checking' or 'savings'. For CC, field is read only. System
 * will identify card_type and generate a value for this field automatically. i.e. visa, mc, disc, amex,
 * jcb, diners.
 * >
 */
class AccountType13
{
    public const SAVINGS = 'savings';

    public const CHECKING = 'checking';
}
