<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Account type. Either "checking" or "savings"
 */
class AccountType12
{
    public const CHECKING = 'checking';

    public const SAVINGS = 'savings';
}
