<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Account Type
 */
class AccountType
{
    public const UNKNOWN = 'unknown';

    public const CHECKING = 'checking';

    public const CREDIT = 'credit';

    public const CASH_BENEFIT = 'cash_benefit';

    public const SNAP = 'snap';

    public const PREPAID = 'prepaid';

    public const SAVINGS = 'savings';

    public const SPENDING_POWER = 'spending_power';

    public const UNIVERSAL = 'universal';
}
