<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Required for ACH transactions if account_vault_id is not provided.
 */
class AchSecCode1
{
    public const CCD = 'CCD';

    public const PPD = 'PPD';

    public const TEL = 'TEL';

    public const WEB = 'WEB';

    public const POP = 'POP';

    public const C21 = 'C21';
}
