<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * SEC code for the account
 */
class AchSecCode3
{
    public const WEB = 'WEB';

    public const CCD = 'CCD';

    public const PPD = 'PPD';

    public const C21 = 'C21';

    public const POP = 'POP';

    public const TEL = 'TEL';
}
