<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * The delivery method of the app to the merchant.
 */
class AppDelivery
{
    public const DIRECT = 'direct';

    public const LINK_FULL_PAGE = 'link_full_page';

    public const LINK_IFRAME = 'link_iframe';
}
