<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * AVS
 */
class Avs
{
    public const BAD = 'BAD';

    public const ZIP = 'ZIP';

    public const STREET = 'STREET';

    public const GOOD = 'GOOD';

    public const UNKNOWN = 'UNKNOWN';
}
