<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

use FortisApiLib\ApiHelper;
use stdClass;

class BroadInfo1 implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $category;

    /**
     * @var string|null
     */
    private $description;

    /**
     * @var string|null
     */
    private $expireDate;

    /**
     * @var string|null
     */
    private $severity;

    /**
     * @var string|null
     */
    private $recipients;

    /**
     * @var string|null
     */
    private $source;

    /**
     * Returns Category.
     */
    public function getCategory(): ?string
    {
        return $this->category;
    }

    /**
     * Sets Category.
     *
     * @maps category
     */
    public function setCategory(?string $category): void
    {
        $this->category = $category;
    }

    /**
     * Returns Description.
     * Information to be broadcasted to the recipients. Accepted value length is maximum 4000 characters.
     * This field is optional.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     * Information to be broadcasted to the recipients. Accepted value length is maximum 4000 characters.
     * This field is optional.
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Expire Date.
     * The date after which the relevance of the broadcasted information (e.g., ceritifacte expiration
     * dates) expires. The accepted value length is 8 characters. The accepted format is YYYYMMDD.
     */
    public function getExpireDate(): ?string
    {
        return $this->expireDate;
    }

    /**
     * Sets Expire Date.
     * The date after which the relevance of the broadcasted information (e.g., ceritifacte expiration
     * dates) expires. The accepted value length is 8 characters. The accepted format is YYYYMMDD.
     *
     * @maps expire_date
     */
    public function setExpireDate(?string $expireDate): void
    {
        $this->expireDate = $expireDate;
    }

    /**
     * Returns Severity.
     */
    public function getSeverity(): ?string
    {
        return $this->severity;
    }

    /**
     * Sets Severity.
     *
     * @maps severity
     */
    public function setSeverity(?string $severity): void
    {
        $this->severity = $severity;
    }

    /**
     * Returns Recipients.
     */
    public function getRecipients(): ?string
    {
        return $this->recipients;
    }

    /**
     * Sets Recipients.
     *
     * @maps recipients
     */
    public function setRecipients(?string $recipients): void
    {
        $this->recipients = $recipients;
    }

    /**
     * Returns Source.
     */
    public function getSource(): ?string
    {
        return $this->source;
    }

    /**
     * Sets Source.
     *
     * @maps source
     */
    public function setSource(?string $source): void
    {
        $this->source = $source;
    }

    /**
     * Converts the BroadInfo1 object to a human-readable string representation.
     *
     * @return string The string representation of the BroadInfo1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'BroadInfo1',
            [
                'category' => $this->category,
                'description' => $this->description,
                'expireDate' => $this->expireDate,
                'severity' => $this->severity,
                'recipients' => $this->recipients,
                'source' => $this->source,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['category', 'description', 'expire_date', 'severity', 'recipients', 'source'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->category)) {
            $json['category']    = $this->category;
        }
        if (isset($this->description)) {
            $json['description'] = $this->description;
        }
        if (isset($this->expireDate)) {
            $json['expire_date'] = $this->expireDate;
        }
        if (isset($this->severity)) {
            $json['severity']    = $this->severity;
        }
        if (isset($this->recipients)) {
            $json['recipients']  = $this->recipients;
        }
        if (isset($this->source)) {
            $json['source']      = $this->source;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
