<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * The Category of the merchant's business
 * >(Required if "business_type" is provided). Note: "business_type" must belong to the appropriate
 * "business_category"
 * >
 */
class BusinessCategory
{
    public const BEAUTY_AND_PERSONAL_CARE = 'beauty_and_personal_care';

    public const CASUAL_USE = 'casual_use';

    public const EDUCATION = 'education';

    public const FOOD_AND_DRINK = 'food_and_drink';

    public const HEALTH_CARE_AND_FITNESS = 'health_care_and_fitness';

    public const HOME_AND_REPAIR = 'home_and_repair';

    public const LEISURE_AND_ENTERTAINMENT = 'leisure_and_entertainment';

    public const NON_PROFIT = 'non_profit';

    public const PROFESSIONAL_SERVICES = 'professional_services';

    public const RETAIL = 'retail';

    public const TRANSPORTATION = 'transportation';
}
