<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * CAU Summary Status ID.
 */
class CauSummaryStatusId
{
    public const ENUM_0 = 0;

    public const ENUM_1 = 1;

    public const ENUM_2 = 2;

    public const ENUM_3 = 3;
}
