<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Length of time that the cardholder has had the account with the 3DS Requestor.
 * >01 - No account
 * >
 * >02 - Created during this transaction
 * >
 * >03 - Less than 30 days
 * >
 * >04 - Between 30 and 60 days
 * >
 * >05 - More than 60 days
 * >
 */
class ChAccAgeInd
{
    public const ENUM_01 = '01';

    public const ENUM_02 = '02';

    public const ENUM_03 = '03';

    public const ENUM_04 = '04';

    public const ENUM_05 = '05';
}
