<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Length of time since the cardholder's account with the 3DS Requestor had a password change or
 * account reset.
 * >01 - No change
 * >
 * >02 - Changed during this transaction
 * >
 * >03 - Less than 30 days
 * >
 * >04 - 30 - 60 days
 * >
 * >05 - More than 60 days
 * >
 */
class ChAccPwChangeInd
{
    public const ENUM_01 = '01';

    public const ENUM_02 = '02';

    public const ENUM_03 = '03';

    public const ENUM_04 = '04';

    public const ENUM_05 = '05';
}
