<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Contact User Default Entry Page
 */
class ContactUserDefaultEntryPage
{
    public const DASHBOARD = 'dashboard';

    public const MAKEPAYMENT = 'makepayment';

    public const PAYMENTHISTORY = 'paymenthistory';

    public const ACCOUNTS = 'accounts';

    public const RECURRINGS = 'recurrings';

    public const INVOICES = 'invoices';
}
