<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * An alpha 2 format country code of US or CA.
 */
class Country
{
    public const US = 'US';

    public const CA = 'CA';
}
