<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Indicates the merchandise delivery timeframe.
 * >01 - Electronic Delivery
 * >
 * >02 - Same day shipping
 * >
 * >03 - Overnight shipping
 * >
 * >04 - Two-day or more shipping
 * >
 */
class DeliveryTimeframe
{
    public const ENUM_01 = '01';

    public const ENUM_02 = '02';

    public const ENUM_03 = '03';

    public const ENUM_04 = '04';
}
