<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Delivery Method
 * >0 - Do not send, use the expand parameter of payment_url in the create paylink request to obtain
 * the payment_url to embed into your messaging system.
 * >
 * >1 - Email. Will send an email to the provided address in the email field.
 * >
 * >2 - SMS. Text message the Paylink. Check with sales rep for cost.
 * >
 * >3 - Both
 * >
 */
class DeliveryMethod
{
    public const ENUM_0 = 0;

    public const ENUM_1 = 1;

    public const ENUM_2 = 2;

    public const ENUM_3 = 3;
}
