<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Deposit Types
 */
class DepositType
{
    public const FEE = 'fee';

    public const DEPOSIT = 'deposit';

    public const ADJUSTMENT = 'adjustment';
}
