<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

class Expand
{
    public const CHANGELOGS = 'changelogs';

    public const POSTBACK_LOGS = 'postback_logs';

    public const PRODUCT_TRANSACTION = 'product_transaction';
}
