<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

class Expand123
{
    public const POSTBACKLOGS = 'postbacklogs';

    public const BASIC_AUTH_USERNAME = 'basic_auth_username';

    public const BASIC_AUTH_PASSWORD = 'basic_auth_password';
}
