<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

class Expand17
{
    public const QUICK_INVOICE_SETTING = 'quick_invoice_setting';

    public const TAGS = 'tags';

    public const QUICK_INVOICE_VIEWS = 'quick_invoice_views';

    public const ALL_TAGS = 'all_tags';

    public const LOCATION = 'location';

    public const CREATED_USER = 'created_user';

    public const MODIFIED_USER = 'modified_user';

    public const CHANGELOGS = 'changelogs';

    public const CONTACT = 'contact';

    public const LOG_EMAILS = 'log_emails';

    public const LOG_SMS = 'log_sms';

    public const TRANSACTIONS = 'transactions';

    public const CC_PRODUCT_TRANSACTION = 'cc_product_transaction';

    public const ACH_PRODUCT_TRANSACTION = 'ach_product_transaction';

    public const EMAIL_BLACKLIST = 'email_blacklist';

    public const SMS_BLACKLIST = 'sms_blacklist';

    public const FILES = 'files';

    public const PAYMENT_URL = 'payment_url';
}
