<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

class Expand26
{
    public const LOG_EMAILS = 'log_emails';

    public const CONTACT = 'contact';

    public const ACCOUNT_VAULT = 'account_vault';

    public const CREATED_USER = 'created_user';

    public const TRANSACTIONS = 'transactions';

    public const SIGNATURE = 'signature';

    public const PAYMENT_SCHEDULE = 'payment_schedule';

    public const LOCATION = 'location';

    public const PRODUCT_TRANSACTION = 'product_transaction';

    public const NEXT_RUN_DATE_MIN = 'next_run_date_min';

    public const NEXT_RUN_DATE_MAX = 'next_run_date_max';

    public const TAGS = 'tags';

    public const ALL_TAGS = 'all_tags';

    public const CHANGELOGS = 'changelogs';

    public const FORECAST = 'forecast';

    public const RECURRING_SPLITS = 'recurring_splits';
}
