<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

class Expand117
{
    public const RECEIVED_EMAILS = 'received_emails';

    public const FEATURE_FLAGS = 'feature_flags';

    public const PRIMARY_LOCATION = 'primary_location';

    public const LOCATIONS = 'locations';

    public const CONTACT = 'contact';

    public const ISDELETABLE = 'isDeletable';

    public const ACTIVE_NOTIFICATION_ALERTS = 'active_notification_alerts';

    public const LOCATION_USERS = 'location_users';

    public const AUTH_ROLES = 'auth_roles';

    public const CONTACT_ID = 'contact_id';

    public const CHANGELOGS = 'changelogs';

    public const RESOURCES = 'resources';

    public const DOMAIN = 'domain';

    public const CREATED_USER = 'created_user';

    public const LOCATION_MARKETPLACES = 'location_marketplaces';

    public const EMAIL_BLACKLIST = 'email_blacklist';

    public const HELPPAGE = 'helppage';
}
