<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

class Expand40
{
    public const LOCATION = 'location';

    public const CREATED_USER = 'created_user';

    public const TERMINAL_APPLICATION = 'terminal_application';

    public const CHANGELOGS = 'changelogs';

    public const TERMINAL_ROUTERS = 'terminal_routers';

    public const HAS_TERMINAL_ROUTERS = 'has_terminal_routers';

    public const TERMINAL_CVM = 'terminal_cvm';

    public const TERMINAL_MANUFACTURER = 'terminal_manufacturer';
}
