<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

class Field59
{
    public const USER_ID = 'user_id';

    public const ID = 'id';

    public const CREATED_TS = 'created_ts';
}
