<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

class Field31
{
    public const LOCATION_ID = 'location_id';

    public const TERMINAL_ID = 'terminal_id';

    public const REQUIRE_SIGNATURE = 'require_signature';

    public const DEVICE_TERM_API_ID = 'device_term_api_id';

    public const TERMS_CONDITIONS = 'terms_conditions';

    public const ID = 'id';

    public const REASON_CODE_ID = 'reason_code_id';

    public const SIGNATURE = 'signature';

    public const CREATED_TS = 'created_ts';

    public const MODIFIED_TS = 'modified_ts';

    public const CREATED_USER_ID = 'created_user_id';

    public const CREATED_USER = 'created_user';

    public const LOCATION = 'location';

    public const TERMINAL = 'terminal';

    public const CHANGELOGS = 'changelogs';

    public const REASON_CODE = 'reason_code';
}
