<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

class Field27
{
    public const ID = 'id';

    public const CREATED_TS = 'created_ts';

    public const PRODUCT_TRANSACTION_ID = 'product_transaction_id';

    public const PROCESSING_STATUS_ID = 'processing_status_id';

    public const BATCH_NUM = 'batch_num';

    public const IS_OPEN = 'is_open';

    public const SETTLEMENT_FILE_NAME = 'settlement_file_name';

    public const BATCH_CLOSE_TS = 'batch_close_ts';

    public const BATCH_CLOSE_DETAIL = 'batch_close_detail';

    public const TOTAL_SALE_AMOUNT = 'total_sale_amount';

    public const TOTAL_SALE_COUNT = 'total_sale_count';

    public const TOTAL_REFUND_AMOUNT = 'total_refund_amount';

    public const TOTAL_REFUND_COUNT = 'total_refund_count';

    public const TOTAL_VOID_AMOUNT = 'total_void_amount';

    public const TOTAL_VOID_COUNT = 'total_void_count';

    public const TOTAL_BLIND_REFUND_AMOUNT = 'total_blind_refund_amount';

    public const TOTAL_BLIND_REFUND_COUNT = 'total_blind_refund_count';

    public const CHANGELOGS = 'changelogs';

    public const POSTBACK_LOGS = 'postback_logs';

    public const PRODUCT_TRANSACTION = 'product_transaction';
}
