<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

class Field53
{
    public const ACCOUNT_HOLDER_NAME = 'account_holder_name';

    public const ACCOUNT_NUMBER = 'account_number';

    public const ACCOUNT_VAULT_API_ID = 'account_vault_api_id';

    public const TOKEN_API_ID = 'token_api_id';

    public const ACCOUNTVAULT_C1 = 'accountvault_c1';

    public const ACCOUNTVAULT_C2 = 'accountvault_c2';

    public const ACCOUNTVAULT_C3 = 'accountvault_c3';

    public const TOKEN_C1 = 'token_c1';

    public const TOKEN_C2 = 'token_c2';

    public const TOKEN_C3 = 'token_c3';

    public const ACH_SEC_CODE = 'ach_sec_code';

    public const BILLING_ADDRESS = 'billing_address';

    public const CONTACT_ID = 'contact_id';

    public const CUSTOMER_ID = 'customer_id';

    public const IDENTITY_VERIFICATION = 'identity_verification';

    public const LOCATION_ID = 'location_id';

    public const PREVIOUS_ACCOUNT_VAULT_API_ID = 'previous_account_vault_api_id';

    public const PREVIOUS_TOKEN_API_ID = 'previous_token_api_id';

    public const PREVIOUS_ACCOUNT_VAULT_ID = 'previous_account_vault_id';

    public const PREVIOUS_TOKEN_ID = 'previous_token_id';

    public const PREVIOUS_TRANSACTION_ID = 'previous_transaction_id';

    public const TERMS_AGREE = 'terms_agree';

    public const TERMS_AGREE_IP = 'terms_agree_ip';

    public const TITLE = 'title';

    public const TOKEN_IMPORT_ID = 'token_import_id';

    public const SECURE_DIRECTORY_SERVER_TRANSACTION_ID = 'secure_directory_server_transaction_id';

    public const SECURE_PROTOCOL_VERSION = 'secure_protocol_version';

    public const SECURE_AUTH_DATA = 'secure_auth_data';

    public const SECURE_COLLECTION_INDICATOR = 'secure_collection_indicator';

    public const THREE_DS_SERVER_TRANS_ID = 'three_ds_server_trans_id';

    public const ACS_TRANSACTION_ID = 'acs_transaction_id';

    public const _JOI = '_joi';

    public const ID = 'id';

    public const ACCOUNT_TYPE = 'account_type';

    public const ACTIVE = 'active';

    public const CAU_SUMMARY_STATUS_ID = 'cau_summary_status_id';

    public const CREATED_TS = 'created_ts';

    public const E_SERIAL_NUMBER = 'e_serial_number';

    public const E_TRACK_DATA = 'e_track_data';

    public const E_FORMAT = 'e_format';

    public const E_KEYED_DATA = 'e_keyed_data';

    public const EXPIRING_IN_MONTHS = 'expiring_in_months';

    public const EXP_DATE = 'exp_date';

    public const FIRST_SIX = 'first_six';

    public const HAS_RECURRING = 'has_recurring';

    public const LAST_FOUR = 'last_four';

    public const MODIFIED_TS = 'modified_ts';

    public const PAYMENT_METHOD = 'payment_method';

    public const TICKET = 'ticket';

    public const TRACK_DATA = 'track_data';

    public const CREATED_USER_ID = 'created_user_id';

    public const CAU_LAST_UPDATED_TS = 'cau_last_updated_ts';

    public const CARD_BIN = 'card_bin';

    public const ROUTING_NUMBER = 'routing_number';

    public const LOCATION = 'location';

    public const CONTACT = 'contact';

    public const TRANSACTIONS = 'transactions';

    public const ACTIVERECURRINGS = 'activeRecurrings';

    public const IS_DELETABLE = 'is_deletable';

    public const SIGNATURE = 'signature';

    public const CREATED_USER = 'created_user';

    public const CHANGELOGS = 'changelogs';

    public const ACCOUNT_VAULT_CAU_LOGS = 'account_vault_cau_logs';

    public const ACCOUNT_VAULT_CAU_PRODUCT_TRANSACTIONS = 'account_vault_cau_product_transactions';
}
