<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

class Field49
{
    public const LOCATION_ID = 'location_id';

    public const DEFAULT_PRODUCT_TRANSACTION_ID = 'default_product_transaction_id';

    public const TERMINAL_APPLICATION_ID = 'terminal_application_id';

    public const TERMINAL_CVM_ID = 'terminal_cvm_id';

    public const TERMINAL_MANUFACTURER_CODE = 'terminal_manufacturer_code';

    public const TITLE = 'title';

    public const MAC_ADDRESS = 'mac_address';

    public const LOCAL_IP_ADDRESS = 'local_ip_address';

    public const PORT = 'port';

    public const SERIAL_NUMBER = 'serial_number';

    public const TERMINAL_NUMBER = 'terminal_number';

    public const TERMINAL_TIMEOUTS = 'terminal_timeouts';

    public const TIP_PERCENTS = 'tip_percents';

    public const LOCATION_API_ID = 'location_api_id';

    public const TERMINAL_API_ID = 'terminal_api_id';

    public const HEADER_LINE_1 = 'header_line_1';

    public const HEADER_LINE_2 = 'header_line_2';

    public const HEADER_LINE_3 = 'header_line_3';

    public const HEADER_LINE_4 = 'header_line_4';

    public const HEADER_LINE_5 = 'header_line_5';

    public const TRAILER_LINE_1 = 'trailer_line_1';

    public const TRAILER_LINE_2 = 'trailer_line_2';

    public const TRAILER_LINE_3 = 'trailer_line_3';

    public const TRAILER_LINE_4 = 'trailer_line_4';

    public const TRAILER_LINE_5 = 'trailer_line_5';

    public const DEFAULT_CHECKIN = 'default_checkin';

    public const DEFAULT_CHECKOUT = 'default_checkout';

    public const DEFAULT_ROOM_RATE = 'default_room_rate';

    public const DEFAULT_ROOM_NUMBER = 'default_room_number';

    public const DEBIT = 'debit';

    public const EMV = 'emv';

    public const CASHBACK_ENABLE = 'cashback_enable';

    public const PRINT_ENABLE = 'print_enable';

    public const SIG_CAPTURE_ENABLE = 'sig_capture_enable';

    public const IS_PROVISIONED = 'is_provisioned';

    public const TIP_ENABLE = 'tip_enable';

    public const VALIDATED_DECRYPTION = 'validated_decryption';

    public const COMMUNICATION_TYPE = 'communication_type';

    public const ACTIVE = 'active';

    public const ID = 'id';

    public const CREATED_TS = 'created_ts';

    public const MODIFIED_TS = 'modified_ts';

    public const LAST_REGISTRATION_TS = 'last_registration_ts';

    public const CREATED_USER_ID = 'created_user_id';

    public const MODIFIED_USER_ID = 'modified_user_id';

    public const LOCATION = 'location';

    public const CREATED_USER = 'created_user';

    public const TERMINAL_APPLICATION = 'terminal_application';

    public const CHANGELOGS = 'changelogs';

    public const TERMINAL_ROUTERS = 'terminal_routers';

    public const HAS_TERMINAL_ROUTERS = 'has_terminal_routers';

    public const TERMINAL_CVM = 'terminal_cvm';

    public const TERMINAL_MANUFACTURER = 'terminal_manufacturer';
}
