<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Options include: api-default
 */
class Format
{
    public const APIDEFAULT = 'api-default';

    public const PARTNER = 'partner';
}
