<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Reporting format, valid values: csv, tsv
 */
class Format1
{
    public const CSV = 'csv';

    public const TSV = 'tsv';
}
