<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Industry Type
 */
class IndustryType
{
    public const ECOMMERCE = 'ecommerce';

    public const RESTAURANT = 'restaurant';

    public const LODGING = 'lodging';

    public const MOTO = 'moto';

    public const RETAIL = 'retail';

    public const ENUM_RETAIL_SELF_SERVE = 'retail self serve';
}
