<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Interval Type
 */
class IntervalType
{
    public const D = 'd';

    public const W = 'w';

    public const M = 'm';
}
