<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Identifies the category of the message for a specific use case.
 * >01 - Payment Authentication (PA)
 * >
 * >02 - Non-Payment Authentication (NPA)
 * >
 * >80 through 99 - PS Specific Values
 * >
 * >80 - MasterCard Identity Check Insights
 * >
 * >85 - MasterCard Identity Check, Production Validation PA
 * >
 * >86 - MasterCard Identity Check, Production Validation NPA
 * >
 */
class MessageCategory
{
    public const ENUM_01 = '01';

    public const ENUM_02 = '02';

    public const ENUM_80 = '80';

    public const ENUM_81 = '81';

    public const ENUM_82 = '82';

    public const ENUM_83 = '83';

    public const ENUM_84 = '84';

    public const ENUM_85 = '85';

    public const ENUM_86 = '86';

    public const ENUM_87 = '87';

    public const ENUM_88 = '88';

    public const ENUM_89 = '89';

    public const ENUM_90 = '90';

    public const ENUM_91 = '91';

    public const ENUM_92 = '92';

    public const ENUM_93 = '93';

    public const ENUM_94 = '94';

    public const ENUM_95 = '95';

    public const ENUM_96 = '96';

    public const ENUM_97 = '97';

    public const ENUM_98 = '98';

    public const ENUM_99 = '99';
}
