<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Sort direction ASC/DESC
 */
class Order
{
    public const ASC = 'asc';

    public const DESC = 'desc';
}
