<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * The Ownership Type of the merchant's business.
 */
class OwnershipType
{
    public const C = 'c';

    public const GOV = 'gov';

    public const LLC = 'llc';

    public const LLP = 'llp';

    public const NP = 'np';

    public const P = 'p';

    public const PO = 'po';

    public const S = 's';

    public const SP = 'sp';

    public const TE = 'te';
}
