<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * the action that will be used by the form when making the payment possible values: sale, auth-only
 */
class PaylinkAction
{
    public const SALE = 'sale';

    public const AUTHONLY = 'auth-only';
}
