<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * 'cc' or 'ach'
 */
class PaymentMethod9
{
    public const CC = 'cc';

    public const ACH = 'ach';
}
