<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Ui Prefs Process Method
 */
class ProcessMethod
{
    public const VIRTUAL_TERMINAL = 'virtual_terminal';

    public const PHYSICAL_TERMINAL = 'physical_terminal';
}
