<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Reason Code Id
 */
class ReasonCodeId
{
    public const ENUM_0 = 0;

    public const ENUM_1000 = 1000;

    public const ENUM_1001 = 1001;

    public const ENUM_1002 = 1002;

    public const ENUM_1003 = 1003;

    public const ENUM_1004 = 1004;

    public const ENUM_1005 = 1005;

    public const ENUM_1200 = 1200;

    public const ENUM_1201 = 1201;

    public const ENUM_1240 = 1240;

    public const ENUM_1301 = 1301;

    public const ENUM_1302 = 1302;

    public const ENUM_1303 = 1303;

    public const ENUM_1304 = 1304;

    public const ENUM_1305 = 1305;

    public const ENUM_1306 = 1306;

    public const ENUM_1307 = 1307;

    public const ENUM_1308 = 1308;

    public const ENUM_1309 = 1309;

    public const ENUM_1310 = 1310;

    public const ENUM_1311 = 1311;

    public const ENUM_1312 = 1312;

    public const ENUM_1313 = 1313;

    public const ENUM_1314 = 1314;

    public const ENUM_1315 = 1315;

    public const ENUM_1316 = 1316;

    public const ENUM_1317 = 1317;

    public const ENUM_1318 = 1318;

    public const ENUM_1319 = 1319;

    public const ENUM_1320 = 1320;

    public const ENUM_1321 = 1321;

    public const ENUM_1322 = 1322;

    public const ENUM_1323 = 1323;

    public const ENUM_1324 = 1324;

    public const ENUM_1325 = 1325;

    public const ENUM_1326 = 1326;

    public const ENUM_1327 = 1327;

    public const ENUM_1328 = 1328;

    public const ENUM_1329 = 1329;

    public const ENUM_1330 = 1330;

    public const ENUM_1331 = 1331;

    public const ENUM_1332 = 1332;

    public const ENUM_1333 = 1333;

    public const ENUM_1334 = 1334;

    public const ENUM_1335 = 1335;

    public const ENUM_1336 = 1336;

    public const ENUM_1337 = 1337;

    public const ENUM_1338 = 1338;

    public const ENUM_1339 = 1339;

    public const ENUM_1340 = 1340;

    public const ENUM_1341 = 1341;

    public const ENUM_1342 = 1342;

    public const ENUM_1343 = 1343;

    public const ENUM_1344 = 1344;

    public const ENUM_1345 = 1345;

    public const ENUM_1346 = 1346;

    public const ENUM_1347 = 1347;

    public const ENUM_1348 = 1348;

    public const ENUM_1349 = 1349;

    public const ENUM_1350 = 1350;

    public const ENUM_1351 = 1351;

    public const ENUM_1352 = 1352;

    public const ENUM_1353 = 1353;

    public const ENUM_1354 = 1354;

    public const ENUM_1355 = 1355;

    public const ENUM_1356 = 1356;

    public const ENUM_1357 = 1357;

    public const ENUM_1358 = 1358;

    public const ENUM_1359 = 1359;

    public const ENUM_1360 = 1360;

    public const ENUM_1361 = 1361;

    public const ENUM_1362 = 1362;

    public const ENUM_1363 = 1363;

    public const ENUM_1364 = 1364;

    public const ENUM_1365 = 1365;

    public const ENUM_1366 = 1366;

    public const ENUM_1367 = 1367;

    public const ENUM_1368 = 1368;

    public const ENUM_1369 = 1369;

    public const ENUM_1370 = 1370;

    public const ENUM_1371 = 1371;

    public const ENUM_1372 = 1372;

    public const ENUM_1373 = 1373;

    public const ENUM_1374 = 1374;

    public const ENUM_1375 = 1375;

    public const ENUM_1376 = 1376;

    public const ENUM_1377 = 1377;

    public const ENUM_1378 = 1378;

    public const ENUM_1379 = 1379;

    public const ENUM_1380 = 1380;

    public const ENUM_1381 = 1381;

    public const ENUM_1382 = 1382;

    public const ENUM_1383 = 1383;

    public const ENUM_1384 = 1384;

    public const ENUM_1385 = 1385;

    public const ENUM_1386 = 1386;

    public const ENUM_1387 = 1387;

    public const ENUM_1388 = 1388;

    public const ENUM_1389 = 1389;

    public const ENUM_1390 = 1390;

    public const ENUM_1391 = 1391;

    public const ENUM_1392 = 1392;

    public const ENUM_1393 = 1393;

    public const ENUM_1394 = 1394;

    public const ENUM_1395 = 1395;

    public const ENUM_1396 = 1396;

    public const ENUM_1397 = 1397;

    public const ENUM_1398 = 1398;

    public const ENUM_1399 = 1399;

    public const ENUM_1500 = 1500;

    public const ENUM_1510 = 1510;

    public const ENUM_1518 = 1518;

    public const ENUM_1520 = 1520;

    public const ENUM_1530 = 1530;

    public const ENUM_1531 = 1531;

    public const ENUM_1540 = 1540;

    public const ENUM_1541 = 1541;

    public const ENUM_1588 = 1588;

    public const ENUM_1599 = 1599;

    public const ENUM_1601 = 1601;

    public const ENUM_1602 = 1602;

    public const ENUM_1603 = 1603;

    public const ENUM_1604 = 1604;

    public const ENUM_1605 = 1605;

    public const ENUM_1606 = 1606;

    public const ENUM_1607 = 1607;

    public const ENUM_1608 = 1608;

    public const ENUM_1609 = 1609;

    public const ENUM_1610 = 1610;

    public const ENUM_1611 = 1611;

    public const ENUM_1612 = 1612;

    public const ENUM_1613 = 1613;

    public const ENUM_1614 = 1614;

    public const ENUM_1615 = 1615;

    public const ENUM_1616 = 1616;

    public const ENUM_1617 = 1617;

    public const ENUM_1618 = 1618;

    public const ENUM_1619 = 1619;

    public const ENUM_1620 = 1620;

    public const ENUM_1621 = 1621;

    public const ENUM_1622 = 1622;

    public const ENUM_1623 = 1623;

    public const ENUM_1624 = 1624;

    public const ENUM_1625 = 1625;

    public const ENUM_1626 = 1626;

    public const ENUM_1627 = 1627;

    public const ENUM_1628 = 1628;

    public const ENUM_1629 = 1629;

    public const ENUM_1630 = 1630;

    public const ENUM_1631 = 1631;

    public const ENUM_1632 = 1632;

    public const ENUM_1640 = 1640;

    public const ENUM_1641 = 1641;

    public const ENUM_1650 = 1650;

    public const ENUM_1651 = 1651;

    public const ENUM_1652 = 1652;

    public const ENUM_1653 = 1653;

    public const ENUM_1654 = 1654;

    public const ENUM_1655 = 1655;

    public const ENUM_1656 = 1656;

    public const ENUM_1657 = 1657;

    public const ENUM_1658 = 1658;

    public const ENUM_1659 = 1659;

    public const ENUM_1660 = 1660;

    public const ENUM_1661 = 1661;

    public const ENUM_1662 = 1662;

    public const ENUM_1663 = 1663;

    public const ENUM_1664 = 1664;

    public const ENUM_1665 = 1665;

    public const ENUM_1666 = 1666;

    public const ENUM_1667 = 1667;

    public const ENUM_1668 = 1668;

    public const ENUM_1701 = 1701;

    public const ENUM_1800 = 1800;

    public const ENUM_1801 = 1801;

    public const ENUM_1802 = 1802;

    public const ENUM_1803 = 1803;

    public const ENUM_1804 = 1804;

    public const ENUM_1805 = 1805;
}
