<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Reason Model
 */
class ReasonModel
{
    public const CONTACT = 'Contact';

    public const TRANSACTION = 'Transaction';

    public const RECURRING = 'Recurring';

    public const USER = 'User';

    public const PRODUCTTRANSACTION = 'ProductTransaction';

    public const TRANSACTIONBATCH = 'TransactionBatch';

    public const QUICKINVOICE = 'QuickInvoice';

    public const DATAEXPORT = 'DataExport';

    public const USERREPORTSCHEDULE = 'UserReportSchedule';

    public const USERREPORT = 'UserReport';

    public const PAYLINK = 'Paylink';
}
