<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Indicates the intended recipient(s) of the broadcasted information. This field is required.
 * >01 - 3DS SDK
 * >
 * >02 - 3DS Server
 * >
 * >03 - DS
 * >
 * >04 - ACS
 * >
 */
class Recipients
{
    public const ENUM_01 = '01';

    public const ENUM_02 = '02';

    public const ENUM_03 = '03';

    public const ENUM_04 = '04';
}
