<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

class RegistrationField
{
    public const ID = 'id';

    public const FIRST_NAME = 'first_name';

    public const LAST_NAME = 'last_name';

    public const ACCOUNT_NUMBER = 'account_number';

    public const EMAIL = 'email';

    public const COMPANY_NAME = 'company_name';

    public const ADDRESS = 'address';

    public const CITY = 'city';

    public const STATE = 'state';

    public const ZIP = 'zip';

    public const HOME_PHONE = 'home_phone';

    public const OFFICE_PHONE = 'office_phone';

    public const OFFICE_EXT_PHONE = 'office_ext_phone';

    public const CELL_PHONE = 'cell_phone';

    public const CONTACT_API_ID = 'contact_api_id';

    public const DATE_OF_BIRTH = 'date_of_birth';
}
