<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Ui Prefs Export Type
 */
class ReportExportType
{
    public const CSV = 'csv';

    public const TSV = 'tsv';

    public const XLS = 'xls';

    public const XLSX = 'xlsx';
}
