<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Resource
 */
class Resource2
{
    public const CONTACT = 'Contact';

    public const LOCATION = 'Location';

    public const QUICKINVOICE = 'QuickInvoice';
}
