<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * The resource you want to subscribe the postbacks to.
 * >Possible values include: 'contact', 'transaction', 'transactionbatch'
 * >
 */
class Resource12
{
    public const CONTACT = 'contact';

    public const TRANSACTION = 'transaction';

    public const TRANSACTIONBATCH = 'transactionbatch';
}
