<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

use FortisApiLib\ApiHelper;
use stdClass;

class ResponseQuickInvoicesCollection implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $type;

    /**
     * @var List10[]|null
     */
    private $list;

    /**
     * @var Links1|null
     */
    private $links;

    /**
     * @var Pagination1|null
     */
    private $pagination;

    /**
     * @var Sort1|null
     */
    private $sort;

    /**
     * Returns Type.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     *
     * @maps type
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns List.
     * Resource Members
     *
     * @return List10[]|null
     */
    public function getList(): ?array
    {
        return $this->list;
    }

    /**
     * Sets List.
     * Resource Members
     *
     * @maps list
     *
     * @param List10[]|null $list
     */
    public function setList(?array $list): void
    {
        $this->list = $list;
    }

    /**
     * Returns Links.
     */
    public function getLinks(): ?Links1
    {
        return $this->links;
    }

    /**
     * Sets Links.
     *
     * @maps links
     */
    public function setLinks(?Links1 $links): void
    {
        $this->links = $links;
    }

    /**
     * Returns Pagination.
     */
    public function getPagination(): ?Pagination1
    {
        return $this->pagination;
    }

    /**
     * Sets Pagination.
     *
     * @maps pagination
     */
    public function setPagination(?Pagination1 $pagination): void
    {
        $this->pagination = $pagination;
    }

    /**
     * Returns Sort.
     */
    public function getSort(): ?Sort1
    {
        return $this->sort;
    }

    /**
     * Sets Sort.
     *
     * @maps sort
     */
    public function setSort(?Sort1 $sort): void
    {
        $this->sort = $sort;
    }

    /**
     * Converts the ResponseQuickInvoicesCollection object to a human-readable string representation.
     *
     * @return string The string representation of the ResponseQuickInvoicesCollection object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ResponseQuickInvoicesCollection',
            [
                'type' => $this->type,
                'list' => $this->list,
                'links' => $this->links,
                'pagination' => $this->pagination,
                'sort' => $this->sort,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['type', 'list', 'links', 'pagination', 'sort'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->type)) {
            $json['type']       = $this->type;
        }
        if (isset($this->list)) {
            $json['list']       = $this->list;
        }
        if (isset($this->links)) {
            $json['links']      = $this->links;
        }
        if (isset($this->pagination)) {
            $json['pagination'] = $this->pagination;
        }
        if (isset($this->sort)) {
            $json['sort']       = $this->sort;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
