<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * ID for the scheme to which the Cardholder's acctNumber belongs to. It will be used to identify the
 * Scheme from the 3DS Server configuration.
 */
class SchemeId
{
    public const VISA = 'Visa';

    public const MASTERCARD = 'Mastercard';

    public const ENUM_AMERICAN_EXPRESS = 'American Express';

    public const DINERS = 'Diners';
}
