<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Status
 */
class Status3
{
    public const PAID = 'paid';

    public const UNPAID = 'unpaid';
}
