<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Tax Surcharge Config
 */
class TaxSurchargeConfig
{
    public const ENUM_2 = 2;

    public const ENUM_3 = 3;
}
