<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Indicates the type of 3RI request. This data element provides additional information to the ACS to
 * determine the best approach for handling a 3RI request.
 *
 * Values 06 through 12 are accepted as well if 3DS Server initiates authentication with EMV 3DS 2.2.0
 * version or greater (required protocol version can be set in the preferred_protocol_version field).
 *
 * Starting from EMV 3DS 2.3.1:
 * Required if device_channel = 03 and message_category = 01 or 02.
 * Values 13 and 14 can be used.
 * >01 - Recurring transaction
 * >
 * >02 - Installment transaction
 * >
 * >03 - Add card
 * >
 * >04 - Maintain card information
 * >
 * >05 - Account verification
 * >
 * >06 - Split/delayed shipment (EMV 3DS 2.2.0 version or greater)
 * >
 * >07 - Top-up (EMV 3DS 2.2.0 version or greater)
 * >
 * >08 - Mail order (EMV 3DS 2.2.0 version or greater)
 * >
 * >09 - Telephone order (EMV 3DS 2.2.0 version or greater)
 * >
 * >10 - Whitelist status check (EMV 3DS 2.2.0 version or greater)
 * >
 * >11 - Other payment (EMV 3DS 2.2.0 version or greater)
 * >
 * >12 - Billing agreement (EMV 3DS 2.2.0 version or greater)
 * >
 * >13 - Device Binding status check (EMV 3DS 2.3.1 version or greater)
 * >
 * >14 - Card Security Code status check (EMV 3DS 2.3.1 version or greater)
 * >
 * >80 through 99 - PS-specific values, regardless of protocol version
 * >
 */
class ThreeRiInd
{
    public const ENUM_01 = '01';

    public const ENUM_02 = '02';

    public const ENUM_03 = '03';

    public const ENUM_04 = '04';

    public const ENUM_05 = '05';

    public const ENUM_06 = '06';

    public const ENUM_07 = '07';

    public const ENUM_08 = '08';

    public const ENUM_09 = '09';

    public const ENUM_10 = '10';

    public const ENUM_11 = '11';

    public const ENUM_12 = '12';

    public const ENUM_13 = '13';

    public const ENUM_14 = '14';

    public const ENUM_80 = '80';

    public const ENUM_81 = '81';

    public const ENUM_82 = '82';

    public const ENUM_83 = '83';

    public const ENUM_84 = '84';

    public const ENUM_85 = '85';

    public const ENUM_86 = '86';

    public const ENUM_87 = '87';

    public const ENUM_88 = '88';

    public const ENUM_89 = '89';

    public const ENUM_90 = '90';

    public const ENUM_91 = '91';

    public const ENUM_92 = '92';

    public const ENUM_93 = '93';

    public const ENUM_94 = '94';

    public const ENUM_95 = '95';

    public const ENUM_96 = '96';

    public const ENUM_97 = '97';

    public const ENUM_98 = '98';

    public const ENUM_99 = '99';
}
