<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Indicates the type of Authentication request. This data element provides additional information to
 * the ACS to determine the best approach for handling an authentication request. This value is used
 * for App-based and Browser flows.
 * >01 - Payment transaction
 * >
 * >02 - Recurring transaction
 * >
 * >03 - Installment transaction
 * >
 * >04 - Add card
 * >
 * >05 - Maintain card
 * >
 * >06 - Cardholder verification as part of EMV token ID&V
 * >
 * >07 - Billing agreement
 * >
 * >80 through 99 - can be used for PS-specific values, regardless of protocol version
 * >
 */
class ThreeDsRequestorAuthenticationInd
{
    public const ENUM_01 = '01';

    public const ENUM_02 = '02';

    public const ENUM_03 = '03';

    public const ENUM_04 = '04';

    public const ENUM_05 = '05';

    public const ENUM_06 = '06';

    public const ENUM_07 = '07';

    public const ENUM_80 = '80';

    public const ENUM_81 = '81';

    public const ENUM_82 = '82';

    public const ENUM_83 = '83';

    public const ENUM_84 = '84';

    public const ENUM_85 = '85';

    public const ENUM_86 = '86';

    public const ENUM_87 = '87';

    public const ENUM_88 = '88';

    public const ENUM_89 = '89';

    public const ENUM_90 = '90';

    public const ENUM_91 = '91';

    public const ENUM_92 = '92';

    public const ENUM_93 = '93';

    public const ENUM_94 = '94';

    public const ENUM_95 = '95';

    public const ENUM_96 = '96';

    public const ENUM_97 = '97';

    public const ENUM_98 = '98';

    public const ENUM_99 = '99';
}
