<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Identifies the type of transaction being authenticated. The values are derived from ISO 8583. This
 * field is required in some markets. Otherwise, the field is optional.
 * >01 - Goods / Service purchase
 * >
 * >03 - Check Acceptance
 * >
 * >10 - Account Funding
 * >
 * >11 - Quasi-Cash Transaction
 * >
 * >28 - Prepaid activation and Loan
 * >
 */
class TransactionType
{
    public const ENUM_01 = '01';

    public const ENUM_03 = '03';

    public const ENUM_10 = '10';

    public const ENUM_11 = '11';

    public const ENUM_28 = '28';
}
