<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Payment type. Must be unique.
 */
class Type29
{
    public const ACH = 'ach';

    public const CC = 'cc';
}
