<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * type of the amount [4S-Healthcare(Visa and MC Only), 4U-Prescription/Rx(Visa and MC Only), 4V-
 * Vision/Optical(Visa Only), 4W-clinic/other qualified medical(Visa Only) ,4X-Dental(Visa Only)].
 */
class Type60
{
    public const CASHBACK = 'cashback';

    public const SURCHARGE = 'surcharge';

    public const HEALTHCARE = 'healthcare';

    public const TRANSIT = 'transit';

    public const RX = 'RX';

    public const VISION = 'vision';

    public const CLINICAL = 'clinical';

    public const COPAY = 'copay';

    public const DENTAL = 'dental';

    public const TAX = 'tax';

    public const FEE = 'fee';
}
