<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Type ID - See type id section for more detail
 */
class TypeId
{
    public const ENUM_20 = 20;

    public const ENUM_21 = 21;

    public const ENUM_22 = 22;

    public const ENUM_30 = 30;

    public const ENUM_40 = 40;

    public const ENUM_50 = 50;
}
