<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * User Type
 */
class UserTypeCode
{
    public const ENUM_200 = 200;

    public const ENUM_250 = 250;

    public const ENUM_300 = 300;

    public const ENUM_400 = 400;

    public const ENUM_500 = 500;

    public const ENUM_600 = 600;

    public const ENUM_700 = 700;

    public const ENUM_800 = 800;

    public const ENUM_900 = 900;

    public const ENUM_1000 = 1000;

    public const ENUM_100 = 100;
}
