<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

use FortisApiLib\ApiHelper;
use stdClass;

class V1TransactionsLevel3VisaRequest implements \JsonSerializable
{
    /**
     * @var Level3Data4
     */
    private $level3Data;

    /**
     * @param Level3Data4 $level3Data
     */
    public function __construct(Level3Data4 $level3Data)
    {
        $this->level3Data = $level3Data;
    }

    /**
     * Returns Level 3 Data.
     */
    public function getLevel3Data(): Level3Data4
    {
        return $this->level3Data;
    }

    /**
     * Sets Level 3 Data.
     *
     * @required
     * @maps level3_data
     */
    public function setLevel3Data(Level3Data4 $level3Data): void
    {
        $this->level3Data = $level3Data;
    }

    /**
     * Converts the V1TransactionsLevel3VisaRequest object to a human-readable string representation.
     *
     * @return string The string representation of the V1TransactionsLevel3VisaRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'V1TransactionsLevel3VisaRequest',
            ['level3Data' => $this->level3Data, 'additionalProperties' => $this->additionalProperties]
        );
    }

    protected $propertyNames = ['level3_data'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['level3_data'] = $this->level3Data;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
