<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

class Values4
{
    public const TOKEN_API_ID = 'token_api_id';

    public const ACCOUNT_VAULT_API_ID = 'account_vault_api_id';
}
