<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

class Values5
{
    public const ACCOUNTVAULT_C1 = 'accountvault_c1';

    public const TOKEN_C1 = 'token_c1';
}
