<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib\Models;

/**
 * Wallet Provider
 */
class WalletProvider
{
    public const GOOGLEPAY = 'GooglePay';

    public const APPLEPAY = 'ApplePay';
}
