<?php

declare(strict_types=1);

/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisApiLib;

use Core\ClientBuilder;
use Core\Utils\CoreHelper;
use FortisApiLib\Authentication\AccessTokenCredentials;
use FortisApiLib\Authentication\AccessTokenCredentialsBuilder;
use FortisApiLib\Authentication\AccessTokenManager;
use FortisApiLib\Authentication\DeveloperIdCredentials;
use FortisApiLib\Authentication\DeveloperIdCredentialsBuilder;
use FortisApiLib\Authentication\DeveloperIdManager;
use FortisApiLib\Authentication\UserApiKeyCredentials;
use FortisApiLib\Authentication\UserApiKeyCredentialsBuilder;
use FortisApiLib\Authentication\UserApiKeyManager;
use FortisApiLib\Authentication\UserIdCredentials;
use FortisApiLib\Authentication\UserIdCredentialsBuilder;
use FortisApiLib\Authentication\UserIdManager;
use FortisApiLib\Controllers\ApplePayValidateMerchantController;
use FortisApiLib\Controllers\AsyncProcessingController;
use FortisApiLib\Controllers\BatchesController;
use FortisApiLib\Controllers\ContactsController;
use FortisApiLib\Controllers\DeclinedRecurringTransactionsController;
use FortisApiLib\Controllers\DeviceTermsController;
use FortisApiLib\Controllers\ElementsController;
use FortisApiLib\Controllers\FullBoardingController;
use FortisApiLib\Controllers\Level3DataController;
use FortisApiLib\Controllers\LocationsController;
use FortisApiLib\Controllers\M3DsAuthenticationController;
use FortisApiLib\Controllers\M3DsTransactionsController;
use FortisApiLib\Controllers\MerchantDepositsController;
use FortisApiLib\Controllers\MerchantDetailsController;
use FortisApiLib\Controllers\OnBoardingController;
use FortisApiLib\Controllers\PaylinksController;
use FortisApiLib\Controllers\PaymentCardReaderTokenController;
use FortisApiLib\Controllers\QuickInvoicesController;
use FortisApiLib\Controllers\RecurringController;
use FortisApiLib\Controllers\SignaturesController;
use FortisApiLib\Controllers\TagsController;
use FortisApiLib\Controllers\TerminalsController;
use FortisApiLib\Controllers\TicketsController;
use FortisApiLib\Controllers\TokensController;
use FortisApiLib\Controllers\TransactionAchRetriesController;
use FortisApiLib\Controllers\TransactionsAchController;
use FortisApiLib\Controllers\TransactionsCashController;
use FortisApiLib\Controllers\TransactionsCreditCardController;
use FortisApiLib\Controllers\TransactionsEbtCardController;
use FortisApiLib\Controllers\TransactionsReadController;
use FortisApiLib\Controllers\TransactionsUpdatesController;
use FortisApiLib\Controllers\UsersController;
use FortisApiLib\Controllers\UserVerificationsController;
use FortisApiLib\Controllers\WebhooksController;
use FortisApiLib\Logging\LoggingConfigurationBuilder;
use FortisApiLib\Logging\RequestLoggingConfigurationBuilder;
use FortisApiLib\Logging\ResponseLoggingConfigurationBuilder;
use FortisApiLib\Proxy\ProxyConfigurationBuilder;
use FortisApiLib\Utils\CompatibilityConverter;
use Unirest\Configuration;
use Unirest\HttpClient;

class FortisApiClient implements ConfigurationInterface
{
    private $asyncProcessing;

    private $batches;

    private $contacts;

    private $declinedRecurringTransactions;

    private $deviceTerms;

    private $elements;

    private $fullBoarding;

    private $locations;

    private $m3DsAuthentication;

    private $m3DsTransactions;

    private $merchantDeposits;

    private $onBoarding;

    private $paylinks;

    private $paymentCardReaderToken;

    private $quickInvoices;

    private $recurring;

    private $signatures;

    private $tags;

    private $terminals;

    private $tickets;

    private $tokens;

    private $transactionAchRetries;

    private $transactionsAch;

    private $transactionsCash;

    private $transactionsCreditCard;

    private $transactionsEbtCard;

    private $transactionsRead;

    private $level3Data;

    private $transactionsUpdates;

    private $userVerifications;

    private $users;

    private $applePayValidateMerchant;

    private $merchantDetails;

    private $webhooks;

    private $userIdManager;

    private $userApiKeyManager;

    private $developerIdManager;

    private $accessTokenManager;

    private $loggingConfigurationBuilder;

    private $proxyConfiguration;

    private $config;

    private $client;

    /**
     * @see FortisApiClientBuilder::init()
     * @see FortisApiClientBuilder::build()
     *
     * @param array $config
     */
    public function __construct(array $config = [])
    {
        $this->config = array_merge(ConfigurationDefaults::_ALL, CoreHelper::clone($config));
        $this->userIdManager = new UserIdManager($this->config);
        $this->userApiKeyManager = new UserApiKeyManager($this->config);
        $this->developerIdManager = new DeveloperIdManager($this->config);
        $this->accessTokenManager = new AccessTokenManager($this->config);
        $loggingConfiguration = null;
        if ($this->config['loggingConfiguration'] instanceof LoggingConfigurationBuilder) {
            $this->loggingConfigurationBuilder = $this->config['loggingConfiguration'];
            $loggingConfiguration = $this->loggingConfigurationBuilder->build();
        }
        $this->proxyConfiguration = $this->config['proxyConfiguration'] ?? ConfigurationDefaults::PROXY_CONFIGURATION;
        $this->client = ClientBuilder::init(
            new HttpClient(Configuration::init($this)->proxyConfiguration($this->proxyConfiguration))
        )
            ->converter(new CompatibilityConverter())
            ->jsonHelper(ApiHelper::getJsonHelper())
            ->apiCallback($this->config['httpCallback'] ?? null)
            ->userAgent('PHP SDK, Version: 1.0.5, on OS {os-info}')
            ->serverUrls(self::ENVIRONMENT_MAP[$this->getEnvironment()], Server::DEFAULT_)
            ->authManagers([
                'user-id' => $this->userIdManager,
                'user-api-key' => $this->userApiKeyManager,
                'developer-id' => $this->developerIdManager,
                'access-token' => $this->accessTokenManager
            ])
            ->loggingConfiguration($loggingConfiguration)
            ->build();
    }

    /**
     * Create a builder with the current client's configurations.
     *
     * @return FortisApiClientBuilder FortisApiClientBuilder instance
     */
    public function toBuilder(): FortisApiClientBuilder
    {
        $builder = FortisApiClientBuilder::init()
            ->timeout($this->getTimeout())
            ->enableRetries($this->shouldEnableRetries())
            ->numberOfRetries($this->getNumberOfRetries())
            ->retryInterval($this->getRetryInterval())
            ->backOffFactor($this->getBackOffFactor())
            ->maximumRetryWaitTime($this->getMaximumRetryWaitTime())
            ->retryOnTimeout($this->shouldRetryOnTimeout())
            ->httpStatusCodesToRetry($this->getHttpStatusCodesToRetry())
            ->httpMethodsToRetry($this->getHttpMethodsToRetry())
            ->environment($this->getEnvironment())
            ->httpCallback($this->config['httpCallback'] ?? null)
            ->proxyConfiguration($this->getProxyConfigurationBuilder());

        $userId = $this->getUserIdCredentialsBuilder();
        if ($userId != null) {
            $builder->userIdCredentials($userId);
        }

        $userApiKey = $this->getUserApiKeyCredentialsBuilder();
        if ($userApiKey != null) {
            $builder->userApiKeyCredentials($userApiKey);
        }

        $developerId = $this->getDeveloperIdCredentialsBuilder();
        if ($developerId != null) {
            $builder->developerIdCredentials($developerId);
        }

        $accessToken = $this->getAccessTokenCredentialsBuilder();
        if ($accessToken != null) {
            $builder->accessTokenCredentials($accessToken);
        }
        $loggingConfigurationBuilder = $this->getLoggingConfigurationBuilder();
        if ($loggingConfigurationBuilder != null) {
            $builder->loggingConfiguration($loggingConfigurationBuilder);
        }
        return $builder;
    }

    public function getTimeout(): int
    {
        return $this->config['timeout'] ?? ConfigurationDefaults::TIMEOUT;
    }

    public function shouldEnableRetries(): bool
    {
        return $this->config['enableRetries'] ?? ConfigurationDefaults::ENABLE_RETRIES;
    }

    public function getNumberOfRetries(): int
    {
        return $this->config['numberOfRetries'] ?? ConfigurationDefaults::NUMBER_OF_RETRIES;
    }

    public function getRetryInterval(): float
    {
        return $this->config['retryInterval'] ?? ConfigurationDefaults::RETRY_INTERVAL;
    }

    public function getBackOffFactor(): float
    {
        return $this->config['backOffFactor'] ?? ConfigurationDefaults::BACK_OFF_FACTOR;
    }

    public function getMaximumRetryWaitTime(): int
    {
        return $this->config['maximumRetryWaitTime'] ?? ConfigurationDefaults::MAXIMUM_RETRY_WAIT_TIME;
    }

    public function shouldRetryOnTimeout(): bool
    {
        return $this->config['retryOnTimeout'] ?? ConfigurationDefaults::RETRY_ON_TIMEOUT;
    }

    public function getHttpStatusCodesToRetry(): array
    {
        return $this->config['httpStatusCodesToRetry'] ?? ConfigurationDefaults::HTTP_STATUS_CODES_TO_RETRY;
    }

    public function getHttpMethodsToRetry(): array
    {
        return $this->config['httpMethodsToRetry'] ?? ConfigurationDefaults::HTTP_METHODS_TO_RETRY;
    }

    public function getEnvironment(): string
    {
        return $this->config['environment'] ?? ConfigurationDefaults::ENVIRONMENT;
    }

    public function getUserIdCredentials(): UserIdCredentials
    {
        return $this->userIdManager;
    }

    public function getUserIdCredentialsBuilder(): ?UserIdCredentialsBuilder
    {
        if (empty($this->userIdManager->getUserId())) {
            return null;
        }
        return UserIdCredentialsBuilder::init($this->userIdManager->getUserId());
    }

    public function getUserApiKeyCredentials(): UserApiKeyCredentials
    {
        return $this->userApiKeyManager;
    }

    public function getUserApiKeyCredentialsBuilder(): ?UserApiKeyCredentialsBuilder
    {
        if (empty($this->userApiKeyManager->getUserApiKey())) {
            return null;
        }
        return UserApiKeyCredentialsBuilder::init($this->userApiKeyManager->getUserApiKey());
    }

    public function getDeveloperIdCredentials(): DeveloperIdCredentials
    {
        return $this->developerIdManager;
    }

    public function getDeveloperIdCredentialsBuilder(): ?DeveloperIdCredentialsBuilder
    {
        if (empty($this->developerIdManager->getDeveloperId())) {
            return null;
        }
        return DeveloperIdCredentialsBuilder::init($this->developerIdManager->getDeveloperId());
    }

    public function getAccessTokenCredentials(): AccessTokenCredentials
    {
        return $this->accessTokenManager;
    }

    public function getAccessTokenCredentialsBuilder(): ?AccessTokenCredentialsBuilder
    {
        if (empty($this->accessTokenManager->getAccessToken())) {
            return null;
        }
        return AccessTokenCredentialsBuilder::init($this->accessTokenManager->getAccessToken());
    }

    public function getLoggingConfigurationBuilder(): ?LoggingConfigurationBuilder
    {
        if (is_null($this->loggingConfigurationBuilder)) {
            return null;
        }
        $config = $this->loggingConfigurationBuilder->getConfiguration();
        return LoggingConfigurationBuilder::init()
            ->level($config['level'])
            ->logger($config['logger'])
            ->maskSensitiveHeaders($config['maskSensitiveHeaders'])
            ->requestConfiguration(RequestLoggingConfigurationBuilder::init()
                ->includeQueryInPath($config['requestConfiguration']['includeQueryInPath'])
                ->body($config['requestConfiguration']['body'])
                ->headers($config['requestConfiguration']['headers'])
                ->includeHeaders(...$config['requestConfiguration']['includeHeaders'])
                ->excludeHeaders(...$config['requestConfiguration']['excludeHeaders'])
                ->unmaskHeaders(...$config['requestConfiguration']['unmaskHeaders']))
            ->responseConfiguration(ResponseLoggingConfigurationBuilder::init()
                ->body($config['responseConfiguration']['body'])
                ->headers($config['responseConfiguration']['headers'])
                ->includeHeaders(...$config['responseConfiguration']['includeHeaders'])
                ->excludeHeaders(...$config['responseConfiguration']['excludeHeaders'])
                ->unmaskHeaders(...$config['responseConfiguration']['unmaskHeaders']));
    }

    /**
     * Get the proxy configuration builder
     */
    public function getProxyConfigurationBuilder(): ProxyConfigurationBuilder
    {
        return ProxyConfigurationBuilder::init($this->proxyConfiguration['address'])
            ->port($this->proxyConfiguration['port'])
            ->tunnel($this->proxyConfiguration['tunnel'])
            ->auth($this->proxyConfiguration['auth']['user'], $this->proxyConfiguration['auth']['pass'])
            ->authMethod($this->proxyConfiguration['auth']['method']);
    }

    /**
     * Get the client configuration as an associative array
     *
     * @see FortisApiClientBuilder::getConfiguration()
     */
    public function getConfiguration(): array
    {
        return $this->toBuilder()->getConfiguration();
    }

    /**
     * Clone this client and override given configuration options
     *
     * @see FortisApiClientBuilder::build()
     */
    public function withConfiguration(array $config): self
    {
        return new self(array_merge($this->config, $config));
    }

    /**
     * Get the base uri for a given server in the current environment.
     *
     * @param string $server Server name
     *
     * @return string Base URI
     */
    public function getBaseUri(string $server = Server::DEFAULT_): string
    {
        return $this->client->getGlobalRequest($server)->getQueryUrl();
    }

    /**
     * Returns Async Processing Controller
     */
    public function getAsyncProcessingController(): AsyncProcessingController
    {
        if ($this->asyncProcessing == null) {
            $this->asyncProcessing = new AsyncProcessingController($this->client);
        }
        return $this->asyncProcessing;
    }

    /**
     * Returns Batches Controller
     */
    public function getBatchesController(): BatchesController
    {
        if ($this->batches == null) {
            $this->batches = new BatchesController($this->client);
        }
        return $this->batches;
    }

    /**
     * Returns Contacts Controller
     */
    public function getContactsController(): ContactsController
    {
        if ($this->contacts == null) {
            $this->contacts = new ContactsController($this->client);
        }
        return $this->contacts;
    }

    /**
     * Returns Declined Recurring Transactions Controller
     */
    public function getDeclinedRecurringTransactionsController(): DeclinedRecurringTransactionsController
    {
        if ($this->declinedRecurringTransactions == null) {
            $this->declinedRecurringTransactions = new DeclinedRecurringTransactionsController($this->client);
        }
        return $this->declinedRecurringTransactions;
    }

    /**
     * Returns Device Terms Controller
     */
    public function getDeviceTermsController(): DeviceTermsController
    {
        if ($this->deviceTerms == null) {
            $this->deviceTerms = new DeviceTermsController($this->client);
        }
        return $this->deviceTerms;
    }

    /**
     * Returns Elements Controller
     */
    public function getElementsController(): ElementsController
    {
        if ($this->elements == null) {
            $this->elements = new ElementsController($this->client);
        }
        return $this->elements;
    }

    /**
     * Returns Full Boarding Controller
     */
    public function getFullBoardingController(): FullBoardingController
    {
        if ($this->fullBoarding == null) {
            $this->fullBoarding = new FullBoardingController($this->client);
        }
        return $this->fullBoarding;
    }

    /**
     * Returns Locations Controller
     */
    public function getLocationsController(): LocationsController
    {
        if ($this->locations == null) {
            $this->locations = new LocationsController($this->client);
        }
        return $this->locations;
    }

    /**
     * Returns M3 Ds Authentication Controller
     */
    public function getM3DsAuthenticationController(): M3DsAuthenticationController
    {
        if ($this->m3DsAuthentication == null) {
            $this->m3DsAuthentication = new M3DsAuthenticationController($this->client);
        }
        return $this->m3DsAuthentication;
    }

    /**
     * Returns M3 Ds Transactions Controller
     */
    public function getM3DsTransactionsController(): M3DsTransactionsController
    {
        if ($this->m3DsTransactions == null) {
            $this->m3DsTransactions = new M3DsTransactionsController($this->client);
        }
        return $this->m3DsTransactions;
    }

    /**
     * Returns Merchant Deposits Controller
     */
    public function getMerchantDepositsController(): MerchantDepositsController
    {
        if ($this->merchantDeposits == null) {
            $this->merchantDeposits = new MerchantDepositsController($this->client);
        }
        return $this->merchantDeposits;
    }

    /**
     * Returns On Boarding Controller
     */
    public function getOnBoardingController(): OnBoardingController
    {
        if ($this->onBoarding == null) {
            $this->onBoarding = new OnBoardingController($this->client);
        }
        return $this->onBoarding;
    }

    /**
     * Returns Paylinks Controller
     */
    public function getPaylinksController(): PaylinksController
    {
        if ($this->paylinks == null) {
            $this->paylinks = new PaylinksController($this->client);
        }
        return $this->paylinks;
    }

    /**
     * Returns Payment Card Reader Token Controller
     */
    public function getPaymentCardReaderTokenController(): PaymentCardReaderTokenController
    {
        if ($this->paymentCardReaderToken == null) {
            $this->paymentCardReaderToken = new PaymentCardReaderTokenController($this->client);
        }
        return $this->paymentCardReaderToken;
    }

    /**
     * Returns Quick Invoices Controller
     */
    public function getQuickInvoicesController(): QuickInvoicesController
    {
        if ($this->quickInvoices == null) {
            $this->quickInvoices = new QuickInvoicesController($this->client);
        }
        return $this->quickInvoices;
    }

    /**
     * Returns Recurring Controller
     */
    public function getRecurringController(): RecurringController
    {
        if ($this->recurring == null) {
            $this->recurring = new RecurringController($this->client);
        }
        return $this->recurring;
    }

    /**
     * Returns Signatures Controller
     */
    public function getSignaturesController(): SignaturesController
    {
        if ($this->signatures == null) {
            $this->signatures = new SignaturesController($this->client);
        }
        return $this->signatures;
    }

    /**
     * Returns Tags Controller
     */
    public function getTagsController(): TagsController
    {
        if ($this->tags == null) {
            $this->tags = new TagsController($this->client);
        }
        return $this->tags;
    }

    /**
     * Returns Terminals Controller
     */
    public function getTerminalsController(): TerminalsController
    {
        if ($this->terminals == null) {
            $this->terminals = new TerminalsController($this->client);
        }
        return $this->terminals;
    }

    /**
     * Returns Tickets Controller
     */
    public function getTicketsController(): TicketsController
    {
        if ($this->tickets == null) {
            $this->tickets = new TicketsController($this->client);
        }
        return $this->tickets;
    }

    /**
     * Returns Tokens Controller
     */
    public function getTokensController(): TokensController
    {
        if ($this->tokens == null) {
            $this->tokens = new TokensController($this->client);
        }
        return $this->tokens;
    }

    /**
     * Returns Transaction Ach Retries Controller
     */
    public function getTransactionAchRetriesController(): TransactionAchRetriesController
    {
        if ($this->transactionAchRetries == null) {
            $this->transactionAchRetries = new TransactionAchRetriesController($this->client);
        }
        return $this->transactionAchRetries;
    }

    /**
     * Returns Transactions Ach Controller
     */
    public function getTransactionsAchController(): TransactionsAchController
    {
        if ($this->transactionsAch == null) {
            $this->transactionsAch = new TransactionsAchController($this->client);
        }
        return $this->transactionsAch;
    }

    /**
     * Returns Transactions Cash Controller
     */
    public function getTransactionsCashController(): TransactionsCashController
    {
        if ($this->transactionsCash == null) {
            $this->transactionsCash = new TransactionsCashController($this->client);
        }
        return $this->transactionsCash;
    }

    /**
     * Returns Transactions Credit Card Controller
     */
    public function getTransactionsCreditCardController(): TransactionsCreditCardController
    {
        if ($this->transactionsCreditCard == null) {
            $this->transactionsCreditCard = new TransactionsCreditCardController($this->client);
        }
        return $this->transactionsCreditCard;
    }

    /**
     * Returns Transactions Ebt Card Controller
     */
    public function getTransactionsEbtCardController(): TransactionsEbtCardController
    {
        if ($this->transactionsEbtCard == null) {
            $this->transactionsEbtCard = new TransactionsEbtCardController($this->client);
        }
        return $this->transactionsEbtCard;
    }

    /**
     * Returns Transactions Read Controller
     */
    public function getTransactionsReadController(): TransactionsReadController
    {
        if ($this->transactionsRead == null) {
            $this->transactionsRead = new TransactionsReadController($this->client);
        }
        return $this->transactionsRead;
    }

    /**
     * Returns Level 3 Data Controller
     */
    public function getLevel3DataController(): Level3DataController
    {
        if ($this->level3Data == null) {
            $this->level3Data = new Level3DataController($this->client);
        }
        return $this->level3Data;
    }

    /**
     * Returns Transactions Updates Controller
     */
    public function getTransactionsUpdatesController(): TransactionsUpdatesController
    {
        if ($this->transactionsUpdates == null) {
            $this->transactionsUpdates = new TransactionsUpdatesController($this->client);
        }
        return $this->transactionsUpdates;
    }

    /**
     * Returns User Verifications Controller
     */
    public function getUserVerificationsController(): UserVerificationsController
    {
        if ($this->userVerifications == null) {
            $this->userVerifications = new UserVerificationsController($this->client);
        }
        return $this->userVerifications;
    }

    /**
     * Returns Users Controller
     */
    public function getUsersController(): UsersController
    {
        if ($this->users == null) {
            $this->users = new UsersController($this->client);
        }
        return $this->users;
    }

    /**
     * Returns Apple Pay Validate Merchant Controller
     */
    public function getApplePayValidateMerchantController(): ApplePayValidateMerchantController
    {
        if ($this->applePayValidateMerchant == null) {
            $this->applePayValidateMerchant = new ApplePayValidateMerchantController($this->client);
        }
        return $this->applePayValidateMerchant;
    }

    /**
     * Returns Merchant Details Controller
     */
    public function getMerchantDetailsController(): MerchantDetailsController
    {
        if ($this->merchantDetails == null) {
            $this->merchantDetails = new MerchantDetailsController($this->client);
        }
        return $this->merchantDetails;
    }

    /**
     * Returns Webhooks Controller
     */
    public function getWebhooksController(): WebhooksController
    {
        if ($this->webhooks == null) {
            $this->webhooks = new WebhooksController($this->client);
        }
        return $this->webhooks;
    }

    /**
     * A map of all base urls used in different environments and servers
     *
     * @var array
     */
    private const ENVIRONMENT_MAP = [
        Environment::PRODUCTION => [Server::DEFAULT_ => 'https://api.sandbox.fortis.tech'],
        Environment::ENVIRONMENT2 => [Server::DEFAULT_ => 'https://api.fortis.tech']
    ];
}
